### ISSUE TITLE
Allow helm template feature

### ISSUE THREAD

**Issue by jakubigla** [fluxcd/helm-operator#102]
**Describe the feature**
In some environments tiller is a no go, hence all helm charts are deployed via `helm template` command. It would be great if this operator allowed that.

**Comment by stefanprodan** [comment]
We are working on Helm v3 support. I don't think we will be supporting helm template since in v3 Tiller has been removed.

**Comment by jakubigla** [comment]
Thanks for the answer @stefanprodan. Is `helm-v3-dev` branch ready to be used on non production environments with no major issues?

**Comment by stefanprodan** [comment]
Yes it is, we did a [workshop](https://helm.workshop.flagger.dev/prerequisites/#helm-operator) at Helm Summit with Helm Operator based on `helm-v3-dev`.  @hiddeco can you point @jakubigla at the latest container build of helm-v3-dev branch?

**Comment by hiddeco** [comment]
This got lost in my notifications, `RC.7` includes Helm 3 support and does no longer require Tiller with `--helm-versions` set to `v3`.
