### ISSUE TITLE
Send chart release notifications upstream from helm operator

### ISSUE THREAD

**Issue by squaremo** [fluxcd/helm-operator#11]
This has come up a couple of times in weave-community slack.

Step one: figure out what should be sent, and when -- neither of these are straight-forward, since usually we are taking action to reconcile states, rather than enacting a user's command.

**Comment by omerlh** [comment]
Any, any update regarding this issue? We just enabled slack notifications for slack, and it's really valuable for us, we would be happy to have the same thing for helm opertator

**Comment by hlascelles** [comment]
Could we start with something as simple as "if a helm release ends in a `failed` state, send a message to a Slack channel"?

**Comment by derrickburns** [comment]
@hiddeco Any progress on this? 

Ideally we would like a single K8s Event that says "Chart X was deployed successfully, all readiness probes probes pass".

**Comment by kingdonb** [comment]
Helm controller in Flux v2 has taken on the mantle of this issue: https://toolkit.fluxcd.io/guides/helm-operator-migration/

There have been recent advancements in the event-based debugging of Helm chart deployments in the latest releases of Helm controller. Please consider upgrading, if you are subscribing to this thread! All new feature development is taking place in Flux v2.

Thanks for using Flux!
