### ISSUE TITLE
Question: How to use common environment variables or shared config-maps across chart

### ISSUE THREAD

**Issue by ingeknudsen** [fluxcd/helm-operator#120]
Not sure if this will become a feature request, or if this is possible with the version we have, or will be possible with the new Kustomize feature. We have started using Flux in development and production clusters. For development we create new clusters on a, almost, weekly basis. All development clusters points to the same branch and config in the repo. Before we installed flux we installed the components to the cluster through a custom script, but we want to move most of this to Flux config. We have started to see that it would be nice to have a mechanism to share config across components. However we struggle when having components in different namespaces and/or where the config for each component is named differently in the different charts. An example of such a config is the **clusterName**. For the first component we flux'ified, our own controller which runs in default namespace, we created a configmap which feeds the values into the Helm-release. For that component the **clusterName** is a top level value in the values file. The second component was Velero, which needed to be inside a velero namespace. The **clusterName** went into the `configuration -> backupStorageLocation -> bucket`. The third component, kubed, would need to has its **clusterName** config in `config -> clusterName`, the fourth, external-dns, gets **clusterName** into `txtOwnerId`. The way we know how to solve this would be to create a config-map for each namespace where there is a component which should be managed by flux, which needs dynamic variables from outside. For components living in the same namespace, to have a shared configmap where the clustername is duplicated to different sections of that configmap.

What would be nice to be able to do was to either:
- Tell flux about cluster global environment variables, through i.e. ``extraEnvs`` that we could set when we install to that specific cluster, and refer to that variable in the Helmrelease when setting the specific value
- Or to have a `configMapKeyRef` to a shared configmap in the cluster. I.e. having a configmap in the default namespace holding all, even if values are duplicated to different sections, cluster global environment variables, and allow flux to read from that configmap

**Comment by hiddeco** [comment]
> Just to clarify, do you think that limitation will be changed in future?

I think having the option to merge values in at a certain level, to make it possible to e.g. duplicate it to different sections, would make sense to add.

Having the option to refer to `ConfigMap` or `Secret` resources in another namespace is something that needs to be well thought out, as without restrictions it can be easily abused by a bad actor.

**Comment by carlpett** [comment]
@hiddeco Re malicious cross-namespace referencing, shouldn't it normal Kubernetes RBAC be enough to mitigate that? If the helm-operator service account has been given access to the relevant secret/configmap, isn't that a signal that anyone with access to that helm-operator is delegated access to the content of those resources?
Are there cases that are "supported"/recommended where a single helm-operator instance is shared between multiple users who can be assumed to have different privileges? Shouldn't they rather have dedicated helm-operator instances?

_edit: s/flux/helm-operator/_
