### ISSUE TITLE
Private Cluster unable to start (Timeout on startup)

### ISSUE THREAD

**Issue by jan-schumacher** [fluxcd/helm-operator#132]
**Describe the bug**
When a Cluster is not able to connect to the stable (googleapis) repository the helm-operator container is not able to start up because the request is hanging in a 30sec timeout and the readinessprobe is not getting ready because the healthz endpoint is not reachable. Also with disabled repositories this is still the case.

**To Reproduce**
Steps to reproduce the behaviour:
0. A K8s Cluster
1. Cut the internet connection or add a firewall rule to disable connection to googleapis.com
2. install helm-operator and fluxcd

**Expected behavior**
The readinessprobe gets ready although there is no connection possible. A configurability for the probes would be handy or a real disable option for repositories

**Comment by hiddeco** [comment]
This is due to the hardcoded import I added in #124. The workaround till the permanent solution is in place is to mount an empty file at the path it imports (`/var/fluxd/helm/repository/repositories.yaml`).

**Comment by hiddeco** [comment]
This has been fixed in #141.
