### ISSUE TITLE
forceUpgrade doesn't work for helm3 operator

### ISSUE THREAD

**Issue by StupidScience** [fluxcd/helm-operator#134]
**Describe the bug**
Looks like `forceUpgrade: true` doesn't work for operator with helm3. Got `failed to upgrade chart for release [release-name]: rendered manifests contain a resource that already exists` errors.

**To Reproduce**
Steps to reproduce the behaviour:
1. Delete helm-release
2. Wait till helm-operator will try to create it
3. Observe errors

**Expected behavior**
If this flag is set operator should recreate resource or skip it's creation.

**Additional context**
Add any other context about the problem here, e.g 
- Helm operator version: docker.io/fluxcd/helm-operator-prerelease:helm-v3-dev-0b11d9d0
- Targeted Helm version: helm3
- Kubernetes version: v1.14.8
- Git provider: GitHub
- Container registry provider: Azure CR

**Comment by stefansedich** [comment]
@StupidScience can you try out `helm-v3-dev-53b6a21d` I wonder if my previous fix to set dry-run to be client only will fix this issue too.

**Comment by StupidScience** [comment]
@stefansedich looks like it is not operator but helm issue - https://github.com/helm/helm/issues/6850 and https://github.com/helm/helm/issues/7082
I'll close this one.
