### ISSUE TITLE
"failed to compose values for chart release" errors

### ISSUE THREAD

**Issue by StupidScience** [fluxcd/helm-operator#135]
**Describe the bug**
All my helm releases got failure message `failed to compose values for chart release` while it looks like everything is working well and upgrades go through.

**To Reproduce**
1. Install or upgrade release
2. Wait a bit
3. Profit

**Expected behavior**
No failure message

**Logs**
Nothing specific.

**Additional context**
Helm operator version: docker.io/fluxcd/helm-operator-prerelease:helm-v3-dev-0b11d9d0
Targeted Helm version: helm3
Kubernetes version: v1.14.8
Git provider: GitHub
Container registry provider: Azure CR

**Comment by hiddeco** [comment]
Can you provide me a copy of one of `HelmRelease` resources, preferably one that makes use of e.g. a `stable` chart?

**Comment by stefansedich** [comment]
@StupidScience `helm-v3-dev-53b6a21d` should fix this issue, I was seeing this issue and https://github.com/fluxcd/helm-operator/pull/131 fixed it right up.
