### ISSUE TITLE
Update go.mod to use flux v1.16

### ISSUE THREAD

**Issue by denysvitali** [fluxcd/helm-operator#136]
**Describe the bug**
Currently it is not possible to use Flux v1.16.0 as a module in a Go package because it relies on helm-operator@v1.0.0-rc2, which in turn relies on flux@v1.15.0, which in turn relies on the docker/distribution@v.0.0.0-0010101000000(...) revision.

```
go: github.com/fluxcd/flux@v1.16.0 requires
	github.com/fluxcd/helm-operator@v1.0.0-rc2 requires
	github.com/fluxcd/flux@v1.15.0 requires
	github.com/docker/distribution@v0.0.0-00010101000000-000000000000: invalid version: unknown revision 000000000000

```

**To Reproduce**
go.mod:

```
module github.com/org/app

go 1.13

require github.com/fluxcd/flux v1.16.0
```

**Expected behavior**
A successful `go get`

**Related issues / commits**
- https://github.com/fluxcd/flux/pull/2590
- https://github.com/fluxcd/flux/commit/dcac6b929501bf668ff5c6836143fd3f14213a36

**Comment by hiddeco** [comment]
Taken care of in #192

**Comment by denysvitali** [comment]
Thanks 👍
