### ISSUE TITLE
Git.path not applied

### ISSUE THREAD

**Issue by adeleglise** [fluxcd/helm-operator#146]
**Describe the bug**
I have two clusters, one for production and one for dev/staging. I have recently merged the gitops code so that I only have one repo to maintain. 

I have reintalled flux and helm-operator, to the them the new repo URL and a git.path for each cluster.

On the prod cluster everything is working fine, however the dev/staging cluster is syncing the whole repo instead of the path specified.

I've check inside the helm-operator pod, in /tmp and I can see that the dev/staging cluster sync the root path of the repo.

**To Reproduce**
Steps to reproduce the behaviour:
0. FluxCD 1.16, helm operator 1.0.0-rc4
1. Install the helm chart with "--set git.path=path"
2. Go inside the helm-operator pod
3. Check the "/tmp/flux-workingXXXXXXX" folder
4. The entire gitops repo is cloned instead of just the path specified.

**Expected behavior**
Only the specified path is cloned/synced.

**Additional context**
The only difference between dev/stg and prod clusters is that the production cluster is configured with helm tls certs.

I used this command on the prod cluster :

```
helm upgrade --install \
    --set rbac.create=true \
    --set helmOperator.create=true \
    --set helmOperator.createCRD=false \
    --set git.url="git@redacted/gitops.git" \
    --set git.path=production \
    --set git.label=production \
    --set-file ssh.known_hosts=/tmp/flux_known_hosts \
    --set helmOperator.tls.enable=true \
    --set helmOperator.tls.verify=false \
    --set helmOperator.tls.secretName=helm-client \
    --set helmOperator.tls.caContent="$(cat ca.pem)" \
    --set helmOperator.tag=1.0.0-rc4 \
    --set-file ssh.known_hosts=/tmp/flux_known_hosts \
    --set registry.excludeImage="docker.io/*\,quay.io/*" \
    --namespace flux \
    flux \
    fluxcd/flux --tls
```

I used this command on the dev/staging cluster :

```
helm install --name flux \
    --set rbac.create=true \
    --set helmOperator.create=true \
    --set git.url="git@redacted/gitops.git" \
    --set git.path=devstg \
    --set git.label=devstg \
    --set helmOperator.tag=1.0.0-rc4 \
    --set-file ssh.known_hosts=/tmp/flux_known_hosts \
    --set registry.excludeImage="docker.io/*\,quay.io/*" \
    --namespace flux fluxcd/flux
```

I've tried multiple times to reinstall. I've tried with quotes around the path name. Still the issue.

**Comment by hiddeco** [comment]
The `git.path` configuration you are referring to has no effect on what the Helm operator does, [as it has no `--git-path` flag](https://docs.fluxcd.io/projects/helm-operator/en/latest/references/operator.html).

For the Helm operator, what is looked at and/or cloned depends on the git configuration(s) inside your `HelmRelease` resources.

**Comment by adeleglise** [comment]
Ok.

But why do I see the root repo in the dev/stg cluster and I see only the inside of the specified folder in the prod cluster ?

**Comment by hiddeco** [comment]
Without knowing more details about your setup it is impossible to tell for me. The Helm operator always uses a full working clone of the Git repository it mirrors for a release, reason for this is that there can be local path references for chart dependencies.

Are you sure the `/tmp/flux-workingXXXXXXX` folders you checked out were in the Helm operator container, and you did not e.g. mix up Flux and Helm operator containers?

**Comment by adeleglise** [comment]
Yeah I'm sure about that. I've done multiple times. However I've rolledback the changes. I will continue to read the documentation and I will merge the code later on. Maybe using git branches. Anyway thanks for your help.
