### ISSUE TITLE
Does the helm-operator handles jobs ?

### ISSUE THREAD

**Issue by Maatary** [fluxcd/helm-operator#153]
I am interested in migrating my kubernetes deployment appraoch to be operator based. In particular using the Helm operator as we are using helm already.

However in my infrastructure we have a lot of jobs, and wonder how does the helm-operator handle jobs spec ?

How does it delete, or replace running job ? a job spec might not change and we just need to run the job again ? So that would not involve any changes in the CR or helmRelease. ....

I'm puzled.

**Comment by hiddeco** [comment]
The Helm operator handles jobs like Helm handles them. I advice you to read the following for [Helm v3](https://helm.sh/docs/topics/charts_hooks/), and [this page for Helm v2](https://v2.helm.sh/docs/charts_hooks/).

**Comment by hiddeco** [comment]
Closing this as the question has been answered, for additional support around the handling of jobs I would advice you to [join our Slack](https://github.com/fluxcd/helm-operator#getting-help).
