### ISSUE TITLE
helm operator fails to reinstall software due to "failed to uninstall release"

### ISSUE THREAD

**Issue by runningman84** [fluxcd/helm-operator#163]
**Describe the bug**
helm operator fails to reinstall software due to "failed to uninstall release". Funny enough chronograf cannot be found using helm ls --all anymore.

**To Reproduce**
Steps to reproduce the behaviour:
1. install chart helm-operator-0.4.0 with version1.0.0-rc5
2. watch for errors

**Expected behavior**
helm operator should just install it

**Logs**
If applicable, please provide logs. In a standard stand-alone installation, you'd get this by running `kubectl logs -n default deploy/flux-helm-operator`.
```
ts=2019-12-25T21:53:27.715327628Z caller=release.go:311 component=release release=chronograf targetNamespace=hass resource=hass:helmrelease/chronograf helmVersion=v2 info="no existing release" action=install
ts=2019-12-25T21:53:29.7407215Z caller=release.go:217 component=release release=chronograf targetNamespace=hass resource=hass:helmrelease/chronograf helmVersion=v2 error="Helm release failed" revision=1.1.0 err="failed to uninstall release, original installation error: validation failed: unable to recognize \"\": no matches for kind \"Deployment\" in version \"extensions/v1beta1\": release: \"chronograf\" not found"
ts=2019-12-25T21:56:23.547889208Z caller=operator.go:309 component=operator info="enqueuing release" resource=hass:helmrelease/chronograf
```

**Additional context**
Add any other context about the problem here, e.g 
- Helm operator version: 1.0.0 rc5
- Kubernetes version: k3s 1.0
- Git provider: github
- Container registry provider: docker hub

**Comment by stefanprodan** [comment]
Kubernetes 1.16 does not support `extensions/v1beta1` anymore, you either update the chronograf Deployment spec to `apps/v1` or downgrade to Kubernetes 1.15

**Comment by runningman84** [comment]
But the error message failed to uninstall is at least misleading?

**Comment by stefanprodan** [comment]
The message comes from the Kubernetes API saying that is unable to recognise the `extensions/v1beta1` version. Helm Operator logs whatever error Kubernetes returns.

**Comment by runningman84** [comment]
Yes that's ok but why is it complaing about uninstalling it?
