### ISSUE TITLE
configureRepositories[0].name requires single quoting the shell command

### ISSUE THREAD

**Issue by jclynny** [fluxcd/helm-operator#165]
**Describe the bug**
When installing the helm operator and setting up custom repositories: https://github.com/fluxcd/helm-operator/blob/master/chart/helm-operator/README.md the documentation should point out that `configureRepositories[0].name` is a string and needs to be single quoted.  Documentation should be updated to state this.

**To Reproduce**
Steps to reproduce the behaviour:
0. What's your setup?
1. Run the following command when installing Helm with custom helm repositories:
`helm upgrade -i helm-operator fluxcd/helm-operator \
--namespace fluxcd \
--set configureRepositories.enable=true \
--set configureRepositories.repositories[0].name=stable \
--set configureRepositories.repositories[0].url=https://kubernetes-charts.storage.googleapis.com \
--set configureRepositories.repositories[1].name=podinfo \
--set configureRepositories.repositories[1].url=https://stefanprodan.github.io/podinfo`

**Expected behavior**
Repository secret should be accepted when passing in via argument.

**Logs**
If applicable, please provide logs. In a standard stand-alone installation, you'd get this by running `kubectl logs -n default deploy/flux-helm-operator`.

**Additional context**
Add any other context about the problem here, e.g 
- Helm operator version: 0.4.0
- Kubernetes version: 1.14.9
- Helm version: 2.14.3

**Comment by stefanprodan** [comment]
Works ok as it is with bash on macOS, what shell are you using?

**Comment by Karnich** [comment]
im getting this with zsh. Everything works fine in Bash tho

**Comment by stefansedich** [comment]
@Karnich ZSH will perform globbing when it encournters the [ and you can either escape with a \ or quote with ' like you are doing.

**Comment by hiddeco** [comment]
I think, given the fact that there are probably quite a lot of ZSH users among us, and the fact that with single quoting it also works fine in `bash`, it would not hurt to change the example.

**Comment by jclynny** [comment]
@stefanprodan I am using ZSH, but I know a lot of Engineers that use ZSH on their workstations.  It does work in bash, however I don't think it would be a bad idea to change or at least mention it in the example as @hiddeco mentioned.
