### ISSUE TITLE
Helm Operator v4 Chart breaks image 0.10.1

### ISSUE THREAD

**Issue by llivingstone** [fluxcd/helm-operator#170]
**Describe the bug**
When using image 0.10.1 of the Helm operator with v4 of the Helm Operator chart, the helm operator cannot run due to the following snippet being merged (a327b6aa2c2e8c83820b1d754e3eab0c18b6ea7e).

```
        {{- if .Values.helm.versions }}
        - --enabled-helm-versions={{ .Values.helm.versions }}
        {{- end }}
```

When upgrading to one of the Helm Operator RC images, the CRD required has changed from `helmreleases.flux.weave.works` to `helmreleases.helm.fluxcd.io`.

The issue with this is that the latest version of Flux (v1.17.0) uses the old `helmreleases.flux.weave.works` CRD it seems so Flux cannot create the HelmReleases for the Helm Operator to pickup.

Removing the `- --enabled-helm-versions={{ .Values.helm.versions }}` argument for this image tag version fixes the issue.

**To Reproduce**
Steps to reproduce the behaviour:
1. Use the latest helm operator chart with image tag set to 0.10.1

**Expected behavior**
Based on the image tag, the chart should filter the arguments required for the version.

I can put a PR together for this, unless i'm missing something fairly obvious!

**Comment by stefanprodan** [comment]
When upgrading set the versions flag to string empty.

**Comment by llivingstone** [comment]
> When upgrading set the versions flag to string empty.

Thanks for the quick reply Stefan. I'll test this shortly.

**Comment by llivingstone** [comment]
Will close this.

Setting `.Values.helm.versions` to an empty string makes it compatible with the 0.10.1 image.

Thanks @stefanprodan
