### ISSUE TITLE
Question - Create a HelmRelease resource but not the chart

### ISSUE THREAD

**Issue by vikas027** [fluxcd/helm-operator#176]
Is there a way (possibly an annotation) to create a `HelmRelease` resource but not create the helm release? I am stuck in a chicken-egg situation where I have multiple helm charts in a git repository, and a few are dependent on _other resources_ (like an external database, secrets, etc). I don't want these helm charts to be released unless the _other resources_ are created.

My idea was to create a HelmRelease resource with an annotation to not release it, and then later on once my other resources (like an external database, secrets, etc) are ready, then I patch the Release file (in git) to update `HelmRelease` resource which would trigger the creation of my helm chart.

Or there is a better way to do it?

**Comment by stefanprodan** [comment]
You can use the `fluxcd.io/ignore: "true"` annotation, when all other charts have been installed set it to `false`.

**Comment by vikas027** [comment]
Thanks @stefanprodan, can you also please let me know where I can find all these options in the documentation? I had tried before creating an issue, but could not find it. Cheers!

**Comment by stefanprodan** [comment]
The ignore option is explained here https://docs.fluxcd.io/en/1.17.0/faq.html#can-i-temporarily-make-flux-ignore-a-manifest

**Comment by vikas027** [comment]
Just a feedback - it would be good to have all options documented on a single page. It is a bit hard to find those as of now IMHO.
