### ISSUE TITLE
Log before performing dry-run

### ISSUE THREAD

**Issue by sfxworks** [fluxcd/helm-operator#202]
**Describe the bug**
I deployed sealed-secrets as an example with the helm3 operator. 

```
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: sealed-secrets
  namespace: integrations
spec:
  releaseName: sealed-secrets
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com
    name: sealed-secrets
    version: 1.6.1
  values:
    networkPolicy: "true"
```

I see this info notice in my logs over and over. It appears that it is doing more than just checking for an upgrade to the chart. It appears to be trying to update even though the latest version of this chart at the time of writing is 1.16.1. 

**To Reproduce**
Steps to reproduce the behaviour:
0. What's your setup?
1. Deploy Fluxcd
2. Deploy Sealed Secrets
3. Tail helm3 operator logs

**Expected behavior**
It to sleep every minute instead of trying to perform a dry run for the chart every 30 or so seconds. 

**Logs**
If applicable, please provide logs. In a standard stand-alone installation, you'd get this by running `kubectl logs -n default deploy/flux-helm-operator`.

```
ts=2020-01-12T21:25:31.652516675Z caller=operator.go:309 component=operator info="enqueuing release" resource=integrations:helmrelease/sealed-secrets
I0112 21:25:31.777086       6 upgrade.go:79] preparing upgrade for sealed-secrets
I0112 21:25:32.566449       6 upgrade.go:87] performing update for sealed-secrets
I0112 21:25:32.584257       6 upgrade.go:220] dry run for sealed-secrets
ts=2020-01-12T21:26:31.653308755Z caller=operator.go:309 component=operator info="enqueuing release" resource=integrations:helmrelease/sealed-secrets
I0112 21:26:31.804012       6 upgrade.go:79] preparing upgrade for sealed-secrets
I0112 21:26:33.439987       6 upgrade.go:87] performing update for sealed-secrets
I0112 21:26:33.464826       6 upgrade.go:220] dry run for sealed-secrets
ts=2020-01-12T21:27:31.653743928Z caller=operator.go:309 component=operator info="enqueuing release" resource=integrations:helmrelease/sealed-secrets
I0112 21:27:31.793029       6 upgrade.go:79] preparing upgrade for sealed-secrets
I0112 21:27:32.616419       6 upgrade.go:87] performing update for sealed-secrets
I0112 21:27:32.643398       6 upgrade.go:220] dry run for sealed-secrets
ts=2020-01-12T21:28:31.654170066Z caller=operator.go:309 component=operator info="enqueuing release" resource=integrations:helmrelease/sealed-secrets
I0112 21:28:31.789550       6 upgrade.go:79] preparing upgrade for sealed-secrets
I0112 21:28:32.640270       6 upgrade.go:87] performing update for sealed-secrets
I0112 21:28:32.667917       6 upgrade.go:220] dry run for sealed-secrets
ts=2020-01-12T21:29:31.654665022Z caller=operator.go:309 component=operator info="enqueuing release" resource=integrations:helmrelease/sealed-secrets
I0112 21:29:31.808116       6 upgrade.go:79] preparing upgrade for sealed-secrets
I0112 21:29:32.574647       6 upgrade.go:87] performing update for sealed-secrets
I0112 21:29:32.603162       6 upgrade.go:220] dry run for sealed-secrets
ts=2020-01-12T21:30:31.654903273Z caller=operator.go:309 component=operator info="enqueuing release" resource=integrations:helmrelease/sealed-secrets
I0112 21:30:31.788544       6 upgrade.go:79] preparing upgrade for sealed-secrets
I0112 21:30:32.597141       6 upgrade.go:87] performing update for sealed-secrets
I0112 21:30:32.616421       6 upgrade.go:220] dry run for sealed-secrets
```

**Additional context**
- Helm operator version: 
1.0.0-rc7
- Targeted Helm version:
3
- Kubernetes version:
1.16
- Git provider:
gitlab
- Container registry provider:
gitlab

**Comment by hiddeco** [comment]
> It appears to be trying to update even though the latest version of this chart at the time of writing is 1.16.1.

It runs a dry-run to confirm the release still equals to what is defined in the `HelmRelease`, so that it can revert any changes made outside of the `HelmRelease`. The output from Helm is a bit confusing as it first logs that it is running an upgrade, and later tells you that the upgrade was a dry-run.

To make this a bit easier to grasp, we should add an additional log entry to tell what (and why) the operator is doing this, before the dry-run is performed.
