### ISSUE TITLE
Helm operator can not find chart version

### ISSUE THREAD

**Issue by anekdoti** [fluxcd/helm-operator#206]
**Describe the bug**
The helm-operator can not find a chart version referended in a HelmRelease custom resource wit the following log entry:
```
ts=2020-01-14T10:45:12.561438738Z caller=release.go:142 component=release release=${RELEASE_NAME} targetNamespace=${NAMESPACE} resource=${NAMESPACE}:helmrelease/${RELEASENAME} helmVersion=v3 error="chart unavailable: chart \"${CHART_NAME}\" matching 1.0.2-prerelease1 not found in ${REPO_ALIAS} index. (try 'helm repo update'): no chart version found for ${CHART_NAME}-1.0.2-prerelease1"
```

On the other hand, when executing a shell in the helm-operator container, one can verify that the correct version is enlisted in the cache yaml for ${REPO_ALIAS}. A helm repo update does not change anything.

Are there any restrictive rules for the version names allowed? The same procedure succeeded with the version 1.0.1-SNAPSHOT .

**To Reproduce**
I'm using helm-operator in version 1.0.0-rc7.
1. Push a chart with the above version name to private helm repository. Verify that the chart is there in the right version.
2. Deploy HelmRelease refering to the chart. 
3. Watch the helm-operator log.

**Expected behavior**
The chart should be deployed in the desired version.

**Logs**
See above.

**Additional context**
Add any other context about the problem here, e.g 
- Helm operator version: 1.0.0-rc7
- Kubernetes version: 1.15
- Git provider: GitLab 
- Container registry provider: Harbor

**Comment by hiddeco** [comment]
Does a manual chart installation for that exact version work using `helm3` in the running container?

**Comment by hiddeco** [comment]
In addition, can you provide the `.spec.chart` of the `HelmRelease`?

**Comment by anekdoti** [comment]
Thank you for your interest. It turns out that `helm3 repo update` works, but that also a manual install with `helm3` fails with the error 
```
Error: failed to download "https://${HARBOR_URL}/chartrepo/${PROJECT}/${CHART_NAME}" (hint: running `helm repo update` may help)
```

The `.spec.chart` is
```
  chart:
    repository: https://${HARBOR_URL}/chartrepo/${PROJECT}/
    version: 1.0.2-prerelease1
    name: ${CHART_NAME}
```
(sorry for all the redactions)

I have username, password and certificate provided in the repositories.yaml. This shouldn't be the issue because already `helm3 repo update` would fail if authentification is not working.

**Comment by anekdoti** [comment]
Hello @hiddeco - I'm sorry for have wasted your time. In the end, I just had a small typo.
