### ISSUE TITLE
Git repo needed credentials now

### ISSUE THREAD

**Issue by derrickburns** [fluxcd/helm-operator#211]
**Describe the bug**
Last night  I switched  from rc2 using helm v2 it to rc7 using helm v3 only.  The new helm operator reads helm charts stored in helm repos but complains that it cannot read helm charts stored in git repos. 

Is this expected?

**Comment by stefanprodan** [comment]
Are you asking if we intentionally broke the git repos auth? if so the answer is no, we have e2e tests covering charts stored in git and RC.7 passed all tests. To further debug this we need the helm-op logs, the instruction on how RC.7 was installed and an example of a HelmRelease. For Helm-op to be able to clone git repos the Flux SSH key must be passed during install time like this: https://github.com/fluxcd/helm-operator/tree/master/chart/helm-operator#use-fluxs-git-deploy-key

**Comment by derrickburns** [comment]
@stefanprodan  thanks for the quick response! I will investigate more on my end before asking for more help. I just wanted to make sure there was no known issue.

**Comment by derrickburns** [comment]
Thank you for the pointer.  I did not understand that a key of some sort is needed for read-only access by the helm operator.  This may be obvious to you and others, but it was not to me. :)

Everything is working now.  Thank you!
