### ISSUE TITLE
Deleting helmrelease can cause helm operator to freeze with no logs

### ISSUE THREAD

**Issue by derrickburns** [fluxcd/helm-operator#216]
In an attempt to repair a conversion from helm v2 to helm v3 gone bad, I frequently deleted helmrelease objects.  This caused the helm operator to freeze.

**Comment by hiddeco** [comment]
Given the removal of a `HelmRelease` makes a call to Helm it is very likely this is a duplicate of #108.

**Comment by hiddeco** [comment]
Let's continue to track this in #108.
