### ISSUE TITLE
Helmrelease spec should contain --history-max for v3 releases

### ISSUE THREAD

**Issue by HaveFun83** [fluxcd/helm-operator#224]
**Describe the feature**
A clear and concise description of the feature.
Currently is it not possible to set the number of helmv3 revision, which defaults to 10.
The --history-max int flag provide this capability  in the helm upgrade command.
**What would the new user story look like?**
New spec historyMax in the helmrelease file should set the number of helm revisions
**Expected behavior**
A clear and concise description of what you expect to happen.
If set the specified number of historyMax revision files should be keep in the cluster

**Comment by HaveFun83** [comment]
Additional info:
The default limit from `--history-max`  are 10 revisions.

**Comment by hiddeco** [comment]
This default is also [set internally (and honored by Helm)](https://github.com/fluxcd/helm-operator/blob/ddd8ed72af1e4086676ab1f6442a35d625086b50/pkg/release/release.go#L22) but not exposed (or made configurable) in the `HelmRelease`.

```console
hidde@baldr:~/Projects/helm-operator$ helm history default-podinfo --max 256
REVISION        UPDATED                         STATUS          CHART           APP VERSION     DESCRIPTION
2               Tue Jan 21 15:41:00 2020        superseded      podinfo-3.1.4   3.1.4           Upgrade complete
3               Tue Jan 21 15:41:40 2020        superseded      podinfo-3.1.4   3.1.4           Upgrade complete
4               Tue Jan 21 15:42:12 2020        superseded      podinfo-3.1.4   3.1.4           Upgrade complete
5               Tue Jan 21 15:42:24 2020        superseded      podinfo-3.1.4   3.1.4           Upgrade complete
6               Tue Jan 21 15:42:35 2020        superseded      podinfo-3.1.4   3.1.4           Upgrade complete
7               Tue Jan 21 15:43:05 2020        superseded      podinfo-3.1.4   3.1.4           Upgrade complete
8               Tue Jan 21 15:43:18 2020        superseded      podinfo-3.1.4   3.1.4           Upgrade complete
9               Tue Jan 21 15:43:35 2020        superseded      podinfo-3.1.4   3.1.4           Upgrade complete
10              Tue Jan 21 15:43:45 2020        superseded      podinfo-3.1.4   3.1.4           Upgrade complete
11              Tue Jan 21 15:43:58 2020        deployed        podinfo-3.1.4   3.1.4           Upgrade complete
```

It should be fairly straight forward to make this configurable, and a contribution for this is welcome.

**Comment by HaveFun83** [comment]
Wow you are awesome. Thanks a lot @stefansedich and @hiddeco . :beers:
