### ISSUE TITLE
Make pkg/install a sub-module and allow setting the Helm versions

### ISSUE THREAD

**Issue by stefanprodan** [fluxcd/helm-operator#238]
Right now using the `install` package as a library in other projects like eksctl means adding Helm Operator as a dependency and that pulls Kubernetes packages, Docker, Helm etc. It would be great if `install` would be a separate go module so that it can be used without having to pull all Helm Operator dependencies. We should also allow setting the Helm versions in the library so that a consumer can decide to use v3 only.

**Comment by 2opremio** [comment]
Fixed by #234

**Comment by 2opremio** [comment]
Oh, hold on, maybe the helm versions bit is not resolved

**Comment by stefanprodan** [comment]
Setting the version was implemented in #246
