### ISSUE TITLE
helm/v3: enrich logger with release metadata

### ISSUE THREAD

**Issue by derrickburns** [fluxcd/helm-operator#240]
```
 2020/01/24 06:02:18 warning: cannot overwrite table with non table for policy (map[])
```

It would be helpful to identify the field that is causing this issue.

**Comment by hiddeco** [comment]
Given the format of the error I do not think the origin is the operator but Helm itself.

**Comment by derrickburns** [comment]
@hiddeco It would be helpful to identify which helm release  originated the error message.

**Comment by stefansedich** [comment]
@derrickburns do you have a particular chart I can apply to repliate this?

**Comment by hiddeco** [comment]
@stefansedich the error mentioned here is as logged by the `infoLogfunc` from `helm/v3`. 

If we’d want to enrich it with for example the `releaseName`, we have to set the logger to a func that includes this value.

**Comment by stefansedich** [comment]
Makes sense, assign this one to me I have a good idea of what to do now.

**Comment by derrickburns** [comment]
This one: 
```
ts=2020-02-13T21:15:01.96169199Z caller=helm.go:69 component=helm version=v3 info="preparing upgrade for pomerium" targetNamespace=pomerium release=pomerium                │
│ 2020/02/13 21:15:02 warning: cannot overwrite table with non table for policy (map[])~
```

:)

**Comment by derrickburns** [comment]
Good job!  This is very helpful.
