### ISSUE TITLE
Retry upgrade after rollback without change to resource

### ISSUE THREAD

**Issue by derrickburns** [fluxcd/helm-operator#241]
@hiddeco 

I think that the guard on whether to retry a release after a rollback is too restrictive:

https://github.com/fluxcd/helm-operator/blob/83c8f80bcde6ab5a38553349c5d75a995be6ee1c/pkg/release/release.go#L326

For example, suppose an install falls because of a timeout or because a dependencies are not satisfied such as a ServiceAccount being missing. None of these will appear as changes in values. 

More generally, a release may fail and be rolled back because of externalities and these externalities may be transient.

I believe that I have encountered precisely these failures.

Is my concern warranted?

**Comment by hiddeco** [comment]
Transient errors were never taken into account while developing the rollback feature, this is thus not a bug but an enhancement request, and the limitation is actually also documented pretty well.

> [When enabled, the Helm operator will detect a faulty upgrade and perform a rollback, **it will not attempt a new upgrade unless it detects a change in values and/or the chart.**](https://docs.fluxcd.io/projects/helm-operator/en/latest/references/helmrelease-custom-resource.html#rollbacks)

Detecting transient errors is going to be cumbersome, and the best way I can think of to still meet your wishes is a boolean option `.spec.rollback.retry` (default `false`), and a counter (`retryCount`) in the status object of the resource.

The counter gets increased after a failed upgrade, and as long as `.spec.rollback.retry == true && retryCount < 3` we retry the upgrade, after a successful upgrade or a detected change in the chart or values the counter resets.

**Comment by derrickburns** [comment]
Ah. Thanks for the clarification.

Your proposed design would be very helpful.

Please tell me. What do I as a cluster administrator do after the helm operator reaches the retry limit? Must I delete the helm release to get it to be reinstalled?

**Comment by derrickburns** [comment]
The more I think about it, the less I see any utility in a retry count. There seem to be only two values of interest: zero and infinity.

**Comment by hiddeco** [comment]
@derrickburns if you have to try till infinity an error is not transient but permanent. If this would happen on a Friday before the weekend en go unnoticed till Monday you would end up with hundreds of useless revisions.

A cluster administrator can simply exec into the pod and perform the release manually using one of the available Helm binaries.

**Comment by derrickburns** [comment]
I guess what I am saying is that if I have an error that I notice and I address the error, then it would be desirable for the helm operator to recover without me taking other action.  

I believe that this is the way the scheduler works. If there is a problem preventing scheduling, it will keep trying to schedule a pod. It does not give up after a fixed number of retries.

**Comment by derrickburns** [comment]
What is the downside to hundreds of useless revisions?

**Comment by hiddeco** [comment]
> I guess what I am saying is that if I have an error that I notice and I address the error, then it would be desirable for the helm operator to recover without me taking other action.

Most of the time this error would originate from a chart or values configuration mistake, Helm is a packaging solution so if this is not the case but it relies on external things to magically exist (CRDs excluded), your charts are not self contained.

Also, given the amount of 'spurious rollback' bug reports I have handled lately, I think most people expect the upgrade attempts to pause at a certain point after rolling back.

> What is the downside to hundreds of useless revisions?

You corrupt the Helm storage as it only keeps track of a limited number of revisions.

---

Would adding an additional field to the `.spec.rollback` e.g. `maxRetries`, which can be set to `0` for an infinite amount of retries (but still defaults to a low number), be sufficient to fulfill your wishes?

**Comment by derrickburns** [comment]
Yessir.

**Comment by derrickburns** [comment]
@hiddeco Here is an example of a class of helm charts that are not self-contained:  any chart that uses service accounts that it does not create.

For example, the `eksctl` tool can create service accounts. These service accounts are not created by a helm chart.  I use this mechanism to create service accounts for use with IAM. 

So while it would be nice for helm charts to be self-contained, this is not always the case.

**Comment by derrickburns** [comment]
I think that a better way to look at the helm operator is as a controller that operates along the same principles as any other K8s controller, i.e. it has a desired state that it is trying to achieve and on each iteration of the loop it attempts to reach that state.

As for the side effects of failed installations, perhaps there is a better way of containing the size of the failures.

**Comment by hiddeco** [comment]
> For example, the eksctl tool can create service accounts. These service accounts are not created by a helm chart. I use this mechanism to create service accounts for use with IAM.

The CRD was an example, I am aware there are other edge-cases where indeed Helm is not a 100% self-contained. My point was that the percentage of failures due to configuration mistakes outside of the `HelmRelease` resource or chart should be pretty slim, and the question is of the weight of this outweighs the technical complexity it would introduce, and the fact that it does not work with the internals of Helm, is worth it. Especially when you can get away dirt-cheap by making it a user configurable thing.

> I think that a better way to look at the helm operator is as a controller that operates along the same principles as any other K8s controller, i.e. it has a desired state that it is trying to achieve and on each iteration of the loop it attempts to reach that state.

I agree, but most Kubernetes controllers do have a bit more freedom however because they are first class citizens where we rely on a third party (Helm) that forces us to adhere to certain rules and/or limitations that we have to work with, or around.

> As for the side effects of failed installations, perhaps there is a better way of containing the size of the failures.

Even if you would apply a exponential back-off strategy (the only thing I can think of at the moment, but it is past 12AM here), the default history limit of 10 would be reached pretty soon.

**Comment by derrickburns** [comment]
All good. I see the constraints that you have to live with. :)

I think your proposal for allowing a special "0" value that means keep retrying would work for me.  

Good job with the tool.

Get some rest!

**Comment by derrickburns** [comment]
BTW, I have hit *all* of the situations that I have described.  What has caused me concern is how I deploy the helm operator in production without a way to recover from rollback. 

You have given me a way to do so, i.e. by "exec into the pod and perform the release manually using one of the available Helm binaries.".  What would that command be (roughly)?  It may be obvious to you, but it is not obvious to me.

**Comment by hiddeco** [comment]
> You have given me a way to do so, i.e. by "exec into the pod and perform the release manually using one of the available Helm binaries.". What would that command be (roughly)? It may be obvious to you, but it is not obvious to me.

On your local machine with access to the cluster it would be as simple as (assuming Helm v3)

```console
helm -n <namespace> -i <release> upgrade --reuse-values <any additional flags> <chart>
```

Within the container the `<chart>` argument depends on the chart source but the command is identical (swap `helm` with `helm3` though). When a Helm repository source is used and it is listed in your `repositories.yaml` (without this you would need the full URL of the chart) you can simply use the alias and chart name. For Git charts you can clone the repository fresh from within the container and use that, or create a working copy from the `/tmp/flux-gitclone<random>` folder.

> BTW, I have hit all of the situations that I have described. What has caused me concern is how I deploy the helm operator in production without a way to recover from rollback.

When the options I mentioned earlier have been implemented exec'ing in the container would no longer be required in case you would hit the `maxLimit` and did not set it to `0`, as this would make it simply possible to refresh the generation of the resource by e.g. increasing the `maxLimit` once you notice and a new upgrade would be attempted [as we use the generation for a cheap check before doing any checks around rollbacks](https://github.com/fluxcd/helm-operator/blob/8105d4cca953e503f80516da45ba35e8ecc9a556/pkg/release/release.go#L334).

**Comment by derrickburns** [comment]
Awesome!

Thx!

**Comment by derrickburns** [comment]
@hiddeco Thank you for adding the new feature.  I enabled it and it works as expected.

FYI, I happened also to be stuck!  In production, the cluster autoscaler decided to relocate some pods while a helm update was happening.  This resulted in a rollback. With the new feature enabled, this is no longer a problem! I installed rc9 and enabled the feature and voila! Thx.
