### ISSUE TITLE
Unexpected interaction between helm-operator and the flink-operator by Lyft

### ISSUE THREAD

**Issue by anekdoti** [fluxcd/helm-operator#243]
**Describe the bug**

The flink-operator by Lyft [https://github.com/lyft/flinkk8soperator](url) controls Apache Flink job clusters by means of FlinkApplication custom resources. 
When such a custom resource is directly applied to a Kubernetes cluster by synching a git repository with FluxCD (variant 1), it is processed correctly by the flink-operator: the Flink job cluster is deployed and goes to state "Running" and then, after completion of its job, to state "SubmittingJob". In the WebUI of the Flink job cluster, the job is first shown as running and later as completed.
However, when the same FlinkApplication custom resource is provided in a Helm chart and applied using a HelmRelease custom resource in the git repository and the helm-operator (variant 2), the Flink job cluster is deployed but remains in state "ClusterStarting", and its job is not started.
It seems that in variant 1, the FlinkApplication custom resource is extended by various fields specific to the flink-operator, while in variant 2 it remains unchanged.

**To Reproduce**
The setup for the flink-operator, the helm chart, and a workload to sync with FluxCD containing the FlinkApplication and the HelmRelease is provided in the repository [https://github.com/anekdoti/flux-helm-flink-operator-interaction](url). In particular, the flink-operator is used in version 0.4.0. 

The FlinkApplication custom resource is taken from the wordcount-operator-example provided in the git repository of the flink-operator.

Steps to reproduce the behaviour:

1. Package the Helm chart and upload it to a Helm repository of your choice. Update the repository referenced in the Helm release under workload accordingly.
1. Setup a Kubernetes cluster with flux (1.15.0) and helm-operator (1.0.0-rc7)
2. Synchronise the workload folder of the mentioned git repository with flux.
3. Observe the state of the two Flink job clusters with `kubectl get flinkapplication`. Note that wordcount-operator-example-with-helm remains in state "ClusterStarting", while wordcount-operator-example-without-helm finally reaches the state "SubmittingJob".

**Expected behavior**

The Flink job clusters should both leave  the state "ClusterRunning" and start the wordcount-operator-example.

**Additional context**

- Flux version: 1.15.0
- Kubernetes version: 1.15
- Git provider: GitHub (for the linked repository), GitLab
- Container registry provider: docker.io

**Comment by anekdoti** [comment]
Hello @hiddeco ,

are there already some news about the bug? Could you reproduce it with my example repository? And can I be of any help?

**Comment by anekdoti** [comment]
The reason for the behaviour described above lies in the strategy the flink-operator uses to identify the deployments it creates from a FlinkApplication custom resource: the flink-operator labels the deployments on creation with a hash value computed from the FlinkApplication custom resource. When the FlinkApplication custom resource is modified later (e.g., the helm-operator adds its annotation `helm.fluxcd.io/antecedent`), the hash value of the FlinkApplication changes, and thus, the deployments previously created cannot be identified anymore (since they are labelled with the old hash value). In individual steps, what happens is the following:

1. The helm-operator creates the FlinkApplication custom resource from a HelmRelease
2. The flink-operator computes a hash value h from the FlinkApplication and creates deployments with the hash value h
3. The helm-operator adds its annotation to the FlinkApplication. The hash value of the FlinkApplication changes from h to another value h'
4. During its reconcilation loop, the flink-operator tries to find deployments with label h'. This fails, since all deployments are still labelled with hash value h.

A patch that filters out the Helm annotation during computation of the hash value works, but is probably not a general solution.

**Comment by hiddeco** [comment]
Going to close this as after having given the available options more thought, I do not think this should be resolved on our side but instead the (Flink) operator should only take their own annotations into account.

If you disagree with this, feel free to re-open so we can discuss options. :tulip:
