### ISSUE TITLE
Repeated dry-run upgrade out of the expected periodic chart sync

### ISSUE THREAD

**Issue by sa-spag** [fluxcd/helm-operator#248]
**Describe the bug**

I updated the Helm Operator to 1.0.0-rc8 and I'm noticing a misbehavior very similar to #218: a single HelmRelease is being dry-run upgraded every minute.

**To Reproduce**

As mentioned, it concerns only 1 HelmRelease in the cluster (out of 50+). I don't see what makes this specific HelmRelease so special as we have others with similar properties:
- its chart has no `requirements.yaml`
- its chart is fetched from a Git repository (every minute as set with `git-poll-interval`)

Also, note that `charts-sync-interval` is set to 10 minutes and the operator honors this value for other HelmReleases as far as I can see. 

**Expected behavior**

All HelmReleases are being dry-run upgraded every `charts-sync-interval`.

**Logs**

Notice how dry-run upgrades are logged every minute (synced with `git-poll-interval`?): 

```
helm-operator-85ff648545-fz4lw flux-helm-operator ts=2020-01-27T09:45:40.205897783Z caller=release.go:342 component=release release=fluxcloud targetNamespace=flux resource=flux:helmrelease/fluxcloud helmVersion=v2 info="performing dry-run upgrade to see if release has diverged"
helm-operator-85ff648545-fz4lw flux-helm-operator ts=2020-01-27T09:45:40.370996303Z caller=release.go:377 component=release release=fluxcloud targetNamespace=flux resource=flux:helmrelease/fluxcloud helmVersion=v2 info="no changes" action=skip
helm-operator-85ff648545-fz4lw flux-helm-operator ts=2020-01-27T09:46:40.35112511Z caller=logwriter.go:28 component=helm version=v2 info="No requirements found in /tmp/flux-working771664979/fluxcloud/charts."
helm-operator-85ff648545-fz4lw flux-helm-operator ts=2020-01-27T09:46:40.521086276Z caller=release.go:342 component=release release=fluxcloud targetNamespace=flux resource=flux:helmrelease/fluxcloud helmVersion=v2 info="performing dry-run upgrade to see if release has diverged"
helm-operator-85ff648545-fz4lw flux-helm-operator ts=2020-01-27T09:46:40.780643135Z caller=release.go:377 component=release release=fluxcloud targetNamespace=flux resource=flux:helmrelease/fluxcloud helmVersion=v2 info="no changes" action=skip
helm-operator-85ff648545-fz4lw flux-helm-operator ts=2020-01-27T09:47:40.644816587Z caller=logwriter.go:28 component=helm version=v2 info="No requirements found in /tmp/flux-working657099670/fluxcloud/charts."
helm-operator-85ff648545-fz4lw flux-helm-operator ts=2020-01-27T09:47:40.849778802Z caller=release.go:342 component=release release=fluxcloud targetNamespace=flux resource=flux:helmrelease/fluxcloud helmVersion=v2 info="performing dry-run upgrade to see if release has diverged"
helm-operator-85ff648545-fz4lw flux-helm-operator ts=2020-01-27T09:47:41.010700479Z caller=release.go:377 component=release release=fluxcloud targetNamespace=flux resource=flux:helmrelease/fluxcloud helmVersion=v2 info="no changes" action=skip
```

In the same fashion, I can see the operator working on it as repeated bumps here:

![Helm Operator](https://user-images.githubusercontent.com/3592135/73165584-617cfb00-40f4-11ea-9b11-20d2fbc8de0d.png)

**Additional context**

- Helm Operator version: 1.0.0-rc8

**Comment by hiddeco** [comment]
> - its chart is fetched from a Git repository (every minute as set with `git-poll-interval`)

The only thing I can think of, given the configured interval you mention, is that there have been commits in the configured source path for this `HelmRelease`, as this would result in the release being scheduled early.

https://github.com/fluxcd/helm-operator/blob/master/pkg/chartsync/git.go#L222
https://github.com/fluxcd/helm-operator/blob/master/pkg/chartsync/git.go#L271-L280

**Comment by sa-spag** [comment]
I forgot to mention that: the chart Git repository remains unchanged.

**Comment by hiddeco** [comment]
@sa-spag in that case, please provide a `HelmRelease` (and Git chart repository) which reproduces the issue. Without this I am afraid I won't be able to track it down.

**Comment by sa-spag** [comment]
I'll try to come up with a minimal setup that triggers the behavior. Thanks for your feedback.

Haven't found a consistent way to reproduce this yet, though I set the `git-poll-interval` to 30s and dry-run upgrades interval on the impacted HelmRelease followed. Gonna keep you updated.

Worth mentioning: I have other HelmReleases that make use of the same Git repository (via different `.spec.chart.path`) and they are not impacted by this issue.

**Comment by hiddeco** [comment]
@sa-spag what is the configured `.spec.chart.path` for your release, and what is the (pseudo-)`tree` of this folder?

**Comment by sa-spag** [comment]
Something like:
```
.
├── some-chart
...
├── fluxcloud
│   ├── .helmignore
│   ├── Chart.yaml
│   ├── Jenkinsfile
│   ├── templates
│   │   ├── _helpers.tpl
│   │   ├── deployment.yaml
│   │   └── service.yaml
│   └── values.yaml
...
└── some-other-chart
```

The HelmRelease being:
```yaml
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: fluxcloud
  namespace: flux # the Helm Operator is running in the same namespace in case it matters
spec:
  releaseName: fluxcloud
  chart:
    git: ssh://git@whatever/charts.git
    path: fluxcloud
```
