### ISSUE TITLE
Add property to disable atomic installation

### ISSUE THREAD

**Issue by mcharriere** [fluxcd/helm-operator#255]
In the early versions of the operator, the installation would not wait for the chart to be ready by default. That could be changed using the rollback property in the HelmRelease.

After [this change](https://github.com/fluxcd/helm-operator/commit/30156d40e1cb4de27f6c945de3af1a72e667e9ad), the default behavior is that, for the installation only, the operator will wait (atomic flag) until the chart is ready. The problem is that there is no way to disable that.

Given the following scenario:

* Repo with several HelmReleases (let's say 15)
* Some charts depend on others.
* The cluster is bootstrapped and automatically installed Flux.
* The Helm operator will start to install each release in no specific order taking 2 at the time.

This will lead to a case in which each installation will fail (for timeout) until the dependencies are meet. At the end, the operator will install everything, but it will take much longer than before.

It would be nice to have the possibility to disable the atomic behavior during the chart installation.

Thanks!

**Comment by runningman84** [comment]
Another improvement would be to have some priority list by namespace. For example kube-system,monitoring this would ensure that kube2iam and the Prometheus crd is there before any real application is installed

**Comment by hiddeco** [comment]
@mcharriere the following pre-release image includes the fix `fluxcd/helm-operator-prerelease:master-f31bd47f`.

**Comment by mcharriere** [comment]
Thanks @hiddeco . I'll test it an let you know how it goes.

**Comment by GODBS** [comment]
Just tested it, works like a charm

**Comment by mcharriere** [comment]
sorry it took me so long to reach you back. indeed it's working perfectly. thanks!! @hiddeco
