### ISSUE TITLE
My resource is not deploying because the status is failed, how do I get out of this state? 

### ISSUE THREAD

**Issue by fliphess** [fluxcd/helm-operator#257]
I currently have some issues rolling out an older, newer or in any way changed helm chart due to the status is failed. How do I get out of this loop? 

Is there a mechanism in fluxctl or using a setting in the spec to get out of this status failed? 
The issue in the chart has been resolved but how do I move forward from there? 

I would love to see some documentation about this.

**Comment by fliphess** [comment]
It happens in: https://github.com/fluxcd/helm-operator/blob/master/pkg/release/release.go#L329

**Comment by hiddeco** [comment]
By upgrading it manually so that the state is healthy again, see: https://github.com/fluxcd/helm-operator/issues/241#issuecomment-578351380

**Comment by fliphess** [comment]
Thanks, I will do that tonight during the service window, I was hoping for a no-downtime fix :)
