### ISSUE TITLE
No RSA host key is known

### ISSUE THREAD

**Issue by 4nte** [fluxcd/helm-operator#268]
**Describe the bug**

Suddenly helm-operator is unable to pull the helm chart repo. 
```
No RSA host key is known for bitbucket.com and you have requested strict checking.\r\nHost key verification failed.\r\nfatal: Could not read from remote repository.\n\nPlease make sure you have the correct access rights\nand the repository exists.\n"
```
It used to work from the beginning, when I installed Flux & helm-oprator, I haven't changed anything in the Flux & helm-operator configuration since.

Helm-operator was installed with the following values
```
$ helm get values helm-operator
git:
  ssh:
    known_hosts: |
      bitbucket.com ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAubiN81eDcafrgMeLzaFPsw2kNvEcqTKl/VqLat/MaB33pZy0y3rJZtnqwR2qOOvbwKZYKiEO1O6VqNEBxKvJJelCq0dTXWT5pbO2gDXC6h6QDXCaHo6pOHGPUy+YBaGQRGuSusMEASYiWunYN0vCAI8QaXnWMXNMdFP3jHAJH0eDsoiGnLPBlBp4TNm6rYI74nMzgz3B9IikW4WVK+dc8KZJZWYjAuORU3jc1c/NPskD2ASinf8v3xnfXeukU0sJ5N6m5E8VLjObPEO+mN2t/FZTMZLiFqPWc/ALSqnMnnhwrNi2rbfg/rd/IpL8Le3pSBne8+seeFVBoGqzHM9yXw==
    secretName: flux-git-deploy
```

As you can see, RSA key for bitbucket is provided through helm values.
 

**To Reproduce**

1. Install helm-operator with a `git.ssh.known_hosts` for your chart repo
2. Everything is working fine, wait a few weeks..
3. Find that helm-operator is unable to clone the helm-chart repo

**Expected behavior**

I expect helm-operator to be able to clone the repo, as it behaved in the beginning.

**Logs**
```
ts=2020-02-05T10:44:25.074061961Z caller=chartsync.go:535 component=chartsync info="chart repo not ready yet" resource=production:helmrelease/gateway-production status=new err="git clone --mirror: fatal: Could not read from remote repository., full output:\n Cloning into bare repository '/tmp/flux-gitclone217835431'...\nNo RSA host key is known for bitbucket.com and you have requested strict checking.\r\nHost key verification failed.\r\nfatal: Could not read from remote repository.\n\nPlease make sure you have the correct access rights\nand the repository exists.\n"
```

**Additional context**

- Helm operator version: (chart)  helm-operator-0.3.0    (app version) 1.0.0-rc4
- Kubernetes version: 1.15
- Git provider: bitbucket
- Helm repository provider: bitbucket

**Comment by 4nte** [comment]
I ran git clone in the helm-operator container, it successfully clones the repo.

```
/home/flux # git clone git@bitbucket.org:XXX/YYY
Cloning into 'locator-helm'...
remote: Counting objects: 4281, done.
remote: Compressing objects: 100% (1748/1748), done.
remote: Total 4281 (delta 2581), reused 4165 (delta 2484)
Receiving objects: 100% (4281/4281), 569.92 KiB | 1.70 MiB/s, done.
Resolving deltas: 100% (2581/2581), done.
```

**Comment by 4nte** [comment]
Deleted the helm-operator pod and now it works. It's still not clear what caused helm-operator not to be able to clone the repo.

**Comment by hiddeco** [comment]
@4nte is everything still working as expected and can I close this issue?

**Comment by 4nte** [comment]
> @4nte is everything still working as expected and can I close this issue?

Yes, so far so good.
