### ISSUE TITLE
Helm chart not ready: `could not resolve hostname` / `name does not resolve`

### ISSUE THREAD

**Issue by boocup** [fluxcd/helm-operator#271]
I am trying to get my Helm Chart working with Flux and got a couple things going on.

It appears my repository is syncing correctly, but my helm chart doesn't launch. Also, there is an error message in the HelmRelease which doesn't sync with what I'm seeing.

When I bash into the flux pod I see that the sync seems to have worked...

bash-5.0# cd /tmp
bash-5.0# ls
flux-gitclone634126936  flux-working953194826

...when I go into the flux-working directory, I see all my files, subectories and all looks well.

But when I describe the HelmRelease file there is an error message stating the remote repository could not be read (yet the clone seems to have worked when I go into the pod).

Status:
  Conditions:
    Last Transition Time:  2020-02-05T17:40:41Z
    Last Update Time:      2020-02-05T17:43:35Z
    Message:               chart not ready: git clone --mirror: fatal: Could not read from remote repository., full output:
 Cloning into bare repository '/tmp/flux-gitclone671647448'...
ssh: Could not resolve hostname github.com:boocup: Name does not resolve
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

-----

Here is a list of the steps I've been using...

kubectl -n kube-system create sa tiller

kubectl create clusterrolebinding tiller-cluster-rule \
    --clusterrole=cluster-admin \
    --serviceaccount=kube-system:tiller

helm init --skip-refresh --upgrade --service-account tiller --history-max 10

helm repo add fluxcd https://charts.fluxcd.io

kubectl apply -f https://raw.githubusercontent.com/fluxcd/helm-operator/master/deploy/flux-helm-release-crd.yaml

ssh-keyscan github.com

helm upgrade -i flux fluxcd/flux \
--set git.url="git@github.com:boocup/Tidal-SaaS-653" \
--set git.branch="flux-setup-test" \
--set-string ssh.known_hosts="github.com ssh-rsa <key>" \
--namespace flux

fluxctl identity --k8s-fwd-ns flux           ...>>> github deployment key

helm upgrade -i helm-operator fluxcd/helm-operator \
--set git.ssh.secretName=flux-git-deploy \
--namespace flux

------

I would hope that my helm chart would be launched, but it is not being launched.

Here is a snippet from the logs...

ts=2020-02-05T17:55:41.3356283Z caller=loop.go:127 component=sync-loop event=refreshed url=ssh://git@github.com/boocup/Tidal-SaaS-653 branch=flux-setup-test HEAD=1b39d43d4096a193fdeb9e04a534652d7f0320da
ts=2020-02-05T17:55:45.4356849Z caller=sync.go:482 method=Sync cmd=apply args= count=2
ts=2020-02-05T17:55:45.6122425Z caller=sync.go:548 method=Sync cmd="kubectl apply -f -" took=176.4857ms err=null output="storageclass.storage.k8s.io/local-storage unchanged\nhelmrelease.helm.fluxcd.io/tidal unchanged"
ts=2020-02-05T17:55:51.9710123Z caller=images.go:17 component=sync-loop msg="polling for new images for automated workloads"
ts=2020-02-05T17:55:52.0416615Z caller=images.go:27 component=sync-loop msg="no automated workloads"

Client: &version.Version{SemVer:"v2.13.1", GitCommit:"618447cbf203d147601b4b9bd7f8c37a5d39fbb4", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.13.1", GitCommit:"618447cbf203d147601b4b9bd7f8c37a5d39fbb4", GitTreeState:"clean"}
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.1", GitCommit:"d224476cd0730baca2b6e357d144171ed74192d6", GitTreeState:"clean", BuildDate:"2020-01-14T21:04:32Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.5", GitCommit:"20c265fef0741dd71a66480e35bd69f18351daea", GitTreeState:"clean", BuildDate:"2019-10-15T19:07:57Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}

**Comment by hiddeco** [comment]
Can you please provide the `HelmRelease` resource that fails to install?

Based on the reported error (`could not resolve hostname github.com:boocup: Name does not resolve`), there seems to be a formatting error with the URL you have provided in the `.spec.chart` of the `HelmRelease`.

Also, it is not required to `ssh-keyscan` for a repository from `github.com`, we scan the SSH servers of the more popular Git providers while building our images, and include those by default.

**Comment by boocup** [comment]
thanks for responding so quickly and the tip. Here is the HelmRelease file based on the ghost example....


apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: tidal
  namespace: default
spec:
  releaseName: tidal
  chart:
    git: ssh://git@github.com:boocup/Tidal-SaaS-653
    ref: flux-setup-test
    path: charts/tidal

**Comment by boocup** [comment]
i bashed in and played around with ssh manually and this worked....

    git: ssh://git@github.com/boocup/Tidal-SaaS-653

....flipped the colon to a slash....I'm going to close this.....thanks!

**Comment by hiddeco** [comment]
For further reference, the shorthand format (`git@example.com:org/repo.git`) only works _without_ a protocol specified. The official format for `ssh://` is `ssh://git@example.com/org/repo.git`.

**Comment by boocup** [comment]
thanks @hiddeco !
