### ISSUE TITLE
Ability to re-attempt failed helm releases before rollback

### ISSUE THREAD

**Issue by adusumillipraveen** [fluxcd/helm-operator#277]
**Describe the feature**
Currently , we  have releases which fail one-off  ( sometimes timed out ) and are not re-attempted if we have rollback enabled on HR.
It would be good to have an option to define "number of re-attempts" before we mark it as rolled back. This is causing us issues in multi cluster environment where apps go out of sync between the clusters when hit by this.

**What would the new user story look like?**

- HelmRelease CRD supports a flag to define maxattempts.
- Helm operator honours the maxattempts field and retries the release before marking a release for rollback/ failure.

**Expected behavior**
Helm operator retries for a given number of max attempts before marking a release as failed/ rollback.

**Comment by hiddeco** [comment]
This sounds a lot like what was described in #241 and implemented in #252. Can you please take a look if this would fulfill your needs? The feature will be included in the next RC.

**Comment by adusumillipraveen** [comment]
Perfect, looks like exactly what we want.
