### ISSUE TITLE
Revamp documentation for 1.0.0 GA

### ISSUE THREAD

**Issue by hiddeco** [fluxcd/helm-operator#279]
The current state of the documentation is at times confusing to users (example #274), and there are some features that are either not documented at all, or lack proper documentation (#18, #54, #222, and https://github.com/fluxcd/helm-operator/issues?utf8=%E2%9C%93&q=+label%3Aquestion+sort%3Aupdated-desc).

Therefore, before making the `1.0.0` GA release, we should:

- [x] Restructure the documentation so that it is easier to grasp for people already familiar with the Helm documentation. What I had in mind is to create a structure like this:

   ```
   Introduction
     Installing the Helm operator
     Operating on `HelmRelease`s
   Topics
     The operator, and Helm
   `HelmRelease` Guide
     Getting Started
     The `HelmRelease`
     Chart Sources
     Values
      Values from Sources
     Upgrades
     Rolling back Releases
     Automation
     Debugging
   How-to
     Trigger a refresh of Git mirrors using the API
   Frequently Asked Questions
   ```

  - [ ] Ensure pages that are removed due to this are replaced by placeholders linking to the new page.
- [x] Ensure all our CRD fields are documented in tables, see [Istio's documentation for an example](https://istio.io/docs/reference/config/networking/destination-rule/).
- [x] Ensure our links to the CRD (`README.md` included) are versioned, as mentioned in https://github.com/fluxcd/helm-operator/issues/231#issuecomment-576801024.
- [x] Rephrase the `README.md` to highlight the fact that the Helm operator can be used as a standalone utility, and is only dependent on Flux for the automation of image updates.

**Comment by hiddeco** [comment]
Rollbacks should be documented better, as enabling results in e.g. the waiting behaviour to be configured, but this is not obvious to users [as reported on Slack](https://cloud-native.slack.com/archives/CLAJ40HV3/p1581560090347500?thread_ts=1581556502.347400&cid=CLAJ40HV3).

**Comment by hiddeco** [comment]
https://github.com/fluxcd/helm-operator/issues/17#issuecomment-586456020

**Comment by kav** [comment]
Might also be nice to have a document describing bootstrapping flux using the helm operator. I've got a basic setup going but having the helm operator as the only thing I manually install to the cluster would be even better. Happy to take a stab at it
