### ISSUE TITLE
Add ability to define priority/order of Helm Releases

### ISSUE THREAD

**Issue by adusumillipraveen** [fluxcd/helm-operator#280]
**Describe the feature**

It would be very useful to have a way to define the order/ priority  in which helm operator should pick up helm releases. This is becoming a big concern while bootstrapping clusters when there are services that are depend on one other. 

**What would the new user story look like?**

1. HelmRelease CRD supports a flag to define priority (Integer property )
2. Helm operator deploys the releases in the order of priority.
3. Helm operator rollbacks or continues on failed releases as it would do today.

**Expected behavior**

Helm Release supports a priority property, which is used by helm operator to decide the order of installing Helm Releases.

**Comment by hiddeco** [comment]
This is out of scope for the operator.

As with native Kubernetes resources (i.e. of kind `Deployment`) they are processed in the order they are applied as the operator makes use of the FIFO queue provided by Kubernetes' `client-go`. Prioritizing this queue would be possible by e.g. checking dependencies and re-queuing the item they aren't met, but this is non-optimal.

I also have to note that anything that fails to install will be retried, so mass-applying everything at once may result in several failures but after a while things should be stable. In addition to this you should bundle closely coupled services in an umbrella chart to ensure they are all rolled out at once.

If this is not sufficient for your bootstrapping scenario you should advocate for such a feature to be included in Flux ([related issue](https://github.com/fluxcd/flux/issues/2758)) as this would solve it on the applier's side for all resource kinds.

**Comment by adusumillipraveen** [comment]
We have been trying to use umbrella charts and is only causing more and more issues with time, especially when they are managed by different teams. And bootstrapping takes really long , which we want to avoid. 
Thanks for the explanation and right reference, I have updated my comments on it.

**Comment by stevehipwell** [comment]
I'd be interested to know if this is still seen as out of scope? I don't see umbrella charts as a viable solution to this, we currently apply our `HR` resources in layers but this requires us to add additional automation which wouldn't be required if we were manually using _Helm_. As the _helm-operator_ is intended for an automated workflow it seem incomplete without the functionality to handle complex scenarios.

A _Flux_ based solution would only work correctly if there was a guarantee of queue ordering based on write order. A _helm-operator_ implementation could provide configuration for dependencies and re-order the queue to make sure that pending dependencies were installed first. Missing dependencies and circular dependency references could be handled as errors.
