### ISSUE TITLE
Improve and/or extend available Prometheus metrics

### ISSUE THREAD

**Issue by sa-spag** [fluxcd/helm-operator#281]
Since the operator refactoring and 82ebc1a re-introduced `release_duration_seconds` metric, it is kind of useless as all sync attempt durations are observed, regardless of the result of `shouldSync`. As a result, plotting...
```
sum(rate(flux_helm_operator_release_duration_seconds_sum{success="true", release_name=~"whatever"}[20m])) by (exported_namespace, release_name)
/
sum(rate(flux_helm_operator_release_duration_seconds_count{success="true",release_name=~"whatever"}[20m])) by (exported_namespace, release_name)
```
... mostly spikes when an actual release happen but then drops back to the dry-run upgrade duration, e.g.:

<img width="1349" alt="Capture d’écran 2020-02-10 à 17 39 51" src="https://user-images.githubusercontent.com/3592135/74170052-96c53500-4c2c-11ea-87c6-2b529d6c2c96.png">

Unless I missed something, I think it would be more useful to track actual upgrades duration separately from dry-run only upgrades (and perhaps some other cases I haven't mentioned here too).

**Comment by hiddeco** [comment]
There have been various reports that this metric is non optimal, including a (now closed) PR to record the release count in #84.

Given this I would like to extend / widen this issue a bit and figure out what would be the most useful metrics to the community so that we can settle everything in one take.

In my opinion the histogram we have now should stay put, but may need some tweaking with regard to the labels it includes so that it is easier to get a subset of data from it. In addition, we may want to introduce a new metric that records the individual duration of Helm actions and the release they were performed for.

What do you think?

**Comment by sa-spag** [comment]
I agree. Also have in mind the discussion in #62, as I think we should not only leverage metrics but events also.
There are some interesting elements on fluxcd/flux#2812, we could benefit from these reasoning efforts.

**Comment by hiddeco** [comment]
> Also have in mind the discussion in #62, as I think we should not only leverage metrics but events also.

I am aware of this issue but would like to focus on a single thing at a time, and keep the scope of issues narrow. This ensures we are able to deliver and/or close issues in a reasonable timeframe with the small amount of workforces we have available.

**Comment by sa-spag** [comment]
Definitely. My point was more about avoiding to cover too much through metrics, as using them is not always the best solution I believe. Let's keep the discussion focussed on these then.

**Comment by sa-spag** [comment]
For the record, I have currently set 3 alert rules up:

The first to alert when releases are `FAILED` using [sstarcher/helm-exporter](https://github.com/sstarcher/helm-exporter):
```yaml
alert: HelmReleaseFailed
expr: min
  by(exported_namespace, release) (helm_chart_info) < 0
```
Perhaps the Helm Operator could somehow expose the same without having to rely on `helm-exporter`?

Then I have this one to make sure the Helm Operator is not "overwhelmed":
```yaml
alert: HelmOperatorLowThroughput
expr: sum
  by(namespace) (flux_helm_operator_release_queue_length_count) > 0
for: 30m
```
There's no addition I can think of on top of my head.

Finally, I use the following to be alerted when the operator fails to sync (as stated on https://github.com/fluxcd/helm-operator/issues/62#issuecomment-563263920):
```yaml
alert: HelmReleaseSyncFailed
expr: sum
  by(exported_namespace, release_name) (max_over_time(max by(exported_namespace, release_name,
  success) (timestamp(changes(flux_helm_operator_release_duration_seconds_count{success="true"}[30s])
  > 0))[1h:1s]) or -max_over_time(max by(exported_namespace, release_name, success)
  (timestamp(changes(flux_helm_operator_release_duration_seconds_count{success="false"}[30s])
  > 0))[1h:1s])) < 0
```
It basically detects the timestamps of the last successful and the last failed sync, applies the difference so a negative value implies the most recent sync failed. Kinda scary, I believe we could do better here (or use events for that purpose).

What is missing is in my opinion is a useable `release_duration_seconds` (but the solutions you suggest go in the good direction), and something that would observe charts download durations. The Git repository case may need to be addressed in a specific way, i.e. have a `git_pull_duration` or something.

Also not covered at the moment is the whole auto-rollback behavior.

**Comment by sa-spag** [comment]
We can close this issue in favor of more granular ones. As far as I am concerned, everything I wanted is now done or covered by other issues, e.g. #344.

**Comment by hiddeco** [comment]
Agree! Feel free to take a stab at your own issue and I'll try to give a timely review.

**Comment by onedr0p** [comment]
@sa-spag would you be willing to share all your PrometheusRules for flux and helm-operator? Also, thanks for adding the metrics covered in sstarcher/helm-exporter.

**Comment by hiddeco** [comment]
@sa-spag feel free to comment on #384 with the rules so they can be included on the monitoring doc page.

**Comment by onedr0p** [comment]
I don't have any rules defined, I was wondering about yours :) I'll be sure to follow that MR.
