### ISSUE TITLE
helm-operator showing "helm-operator Helm release failed error"

### ISSUE THREAD

**Issue by boocup** [fluxcd/helm-operator#286]
**Describe the bug**

helm-operator showing "helm-operator Helm release failed error"...err="release tidal failed: timed out waiting for the condition"

**To Reproduce**

deploy flux
deploy helm-operator
watch helm-operator log
Note: if I bash into the helm-operator pod and move to tmp, I can see the repo files pulled down, so that seems to imply the git repo is reachable.

**Expected behavior**

helm chart app should launch and show...
info="Helm release sync succeeded" revision=937d87300eb99abbcefeb481ae8bf403461a07e0

**Logs**

component=helm version=v2 warning="installation failed with atomic flag set, uninstalling release"
component=release release=tidal targetNamespace=default resource=default:helmrelease/tidal helmVersion=v2 error="Helm release failed" err="release tidal failed: timed out waiting for the condition"
component=helm version=v2 info="No requirements found in /tmp/flux-working956811126/charts/tidal/charts."
component=release release=tidal targetNamespace=default resource=default:helmrelease/tidal helmVersion=v2 info="no existing release" action=install

**Additional context**

- Helm operator version: 2.13
- Kubernetes version: 1.15
- Git provider: GitHub.com

**Comment by boocup** [comment]
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: tidal
  namespace: default
spec:
  releaseName: tidal
  chart:
    git: git@github.com:boocup/Tidal-SaaS-653
    ref: master
    path: charts/tidal

**Comment by hiddeco** [comment]
Can you please join our [CNCF Slack](https://slack.cncf.io) channel `#flux` for issues like this? As they likely aren't bug reports but configuration errors, and they cause a lot of noise for us maintainers.

In addition, you may receive help from other community members there instead of having to wait for a response from us maintainers, which will likely help you fix the issues faster.

**Comment by boocup** [comment]
absolutely
