### ISSUE TITLE
HelmRelease status seems incorrect

### ISSUE THREAD

**Issue by aleclerc-sonrai** [fluxcd/helm-operator#293]
**Describe the bug**

Helm Status is not correctly updated

**To Reproduce**

HelmRelease status is misleading 

**Expected behavior**

`kubectl get hr` would indicate HelmRelease is deployed OK

**Logs**

i have a bunch of helmreleases that don’t seem to have an updated status in the CRD:
```NAMESPACE     NAME                           RELEASE                        STATUS     MESSAGE                                                                                                                                                                        AGE
fluentd       fluentd-daemonset              fluentd-daemonset              deployed   failed to retrieve release [fluentd-daemonset]: context deadline exceeded                                                                                                      2d
kube-system   cluster-autoscaler             cluster-autoscaler             deployed   failed to retrieve release [cluster-autoscaler]: context deadline exceeded                                                                                                     2d
kube-system   cluster-overprovisioner        cluster-overprovisioner        deployed   Could not get apiVersions from Kubernetes: unable to retrieve the complete list of server APIs: metrics.k8s.io/v1beta1: the server is currently unable to handle the request   2d
kube-system   fluentd-aggregator             fluentd-aggregator             deployed   Could not get apiVersions from Kubernetes: unable to retrieve the complete list of server APIs: metrics.k8s.io/v1beta1: the server is currently unable to handle the request   2d
kube-system   k8s-spot-termination-handler   k8s-spot-termination-handler   deployed   Could not get apiVersions from Kubernetes: unable to retrieve the complete list of server APIs: metrics.k8s.io/v1beta1: the server is currently unable to handle the request   2d
kube-system   kube-metrics-adapter           kube-metrics-adapter           deployed   failed to retrieve release [kube-metrics-adapter]: context deadline exceeded                                                                                                   2d
kube-system   kube2iam                       kube2iam                       deployed   failed to retrieve release [kube2iam]: context deadline exceeded                                                                                                               2d
```
Helm-operator still seem to be deploying ok :
```ts=2020-02-12T19:15:05.909801067Z caller=logwriter.go:28 component=helm version=v2 info="No requirements found in /tmp/flux-working343547766/charts/fluentd-daemonset/charts."
ts=2020-02-12T19:15:12.583641107Z caller=release.go:342 component=release release=fluentd-daemonset targetNamespace=fluentd resource=fluentd:helmrelease/fluentd-daemonset helmVersion=v2 info="performing dry-run upgrade to see if release has diverged"
ts=2020-02-12T19:15:25.440534136Z caller=release.go:377 component=release release=fluentd-daemonset targetNamespace=fluentd resource=fluentd:helmrelease/fluentd-daemonset helmVersion=v2 info="no changes" action=skip
```
but status is definitly wrong on the crd:
```status:
  conditions:
  - lastTransitionTime: "2020-02-12T14:42:02Z"
    lastUpdateTime: "2020-02-12T14:43:26Z"
    message: 'failed to retrieve release [fluentd-daemonset]: context deadline exceeded'
    reason: HelmClientError
    status: "False"
    type: Released
```
and helm thinks its ok 
```helm list fluentd-daemonset        
NAME             	REVISION	UPDATED                 	STATUS  	CHART                  	APP VERSION	NAMESPACE
fluentd-daemonset	2       	Mon Feb 10 15:22:12 2020	DEPLOYED	fluentd-daemonset-1.0.0	           	fluentd
```
**Additional context**

- Helm operator version: 1.0.0-rc8
- Kubernetes version: 1.14
- Git provider:
- Helm repository provider:

**Comment by carlpett** [comment]
I see a similar issue as well, where we updated prometheus-operator CRDs by deleting them and then applying them again. For the HelmRelease objects that were synced while the CRDs were not registered, they set a status `failed to upgrade chart for release [kube-state-metrics]: unable to recognize "": no matches for kind "PodMonitor" in version "monitoring.coreos.com/v1"`.
When the CRDs reappear, it seems helm-operator notices that there are no changes needed **and does not clear the status**.

```json
{"caller":"helm.go:69","component":"helm","info":"preparing upgrade for kube-state-metrics","release":"kube-state-metrics","targetNamespace":"monitoring","ts":"2020-03-19T08:01:20.247420385Z","version":"v3"}
{"caller":"helm.go:69","component":"helm","info":"performing update for kube-state-metrics","release":"kube-state-metrics","targetNamespace":"monitoring","ts":"2020-03-19T08:01:21.407445503Z","version":"v3"}
{"caller":"helm.go:69","component":"helm","info":"dry run for kube-state-metrics","release":"kube-state-metrics","targetNamespace":"monitoring","ts":"2020-03-19T08:01:21.446161154Z","version":"v3"}
{"action":"skip","caller":"release.go:404","component":"release","helmVersion":"v3","info":"no changes","release":"kube-state-metrics","resource":"monitoring:helmrelease/kube-state-metrics","targetNamespace":"monitoring","ts":"2020-03-19T08:01:21.452855415Z"}
```

@stefanprodan @hiddeco does this seem like a likely explanation? Should a dry-run that ends without changes or errors set HelmSuccess=true, even if a previous run failed?

**Comment by hiddeco** [comment]
The reported status in `kubectl get helmrelease` is the status for the release _as reported by Helm_, while the given error is the result of the release operation itself. More detailed status updates to the `HelmRelease` and additional Prometheus metrics will arrive when #334 is merged.

@carlpett the comparison is made on the release state as given by Helm, and not by looking at live cluster-state. Given this, it will not have noticed the removal of the CRDs.

> Should a dry-run that ends without changes or errors set HelmSuccess=true, even if a previous run failed?

This is correct.

**Comment by carlpett** [comment]
@hiddeco I think either you misunderstood me, or I am misunderstanding you :) My final sentence wasn't a question so much as a suggestion, perhaps, because this behaviour is currently **not** what I'm seeing.

Here's my setup, and what I observed. We have a single repo with this structure:
```
- charts/
|  + chart A/
|  + chart B/
|  - ...
+ releases/
  + chart-a.yaml
  + chart-b.yaml
  ..
```

Flux watches the releases directory, which just contains HelmRelease objects. All the HelmReleases have a git reference to the very same repo, which helm-operator installs from.

What I observed is that when I removed the Prometheus CRDs out-of-band with kubectl, all the releases managed by helm-operator started to fail to render when helm-operator tried to sync. This set the error status on the HelmRelease objects.

I then reinstalled the CRDs. The dry-runs that the helm-operator does to check if anything needs to happen now pass without any planned changes. It therefore does nothing, **including** not clearing the error status. The error remains until I force some minor change which causes an actual sync to run.

As I understand your response, this is not what is supposed to happen?

**Comment by tommasopozzetti** [comment]
I am seeing the same problem. It seems that in general, if an error occurs while the helm-operator performs helm operations to check the status of a given helm release, the error gets logged in the "MESSAGE" field of the corresponding HelmRelease resource. However, upon resolution of the error, the error message remains there until an upgrade is required.
As @carlpett mentioned, it seems that, when the helm-operator is able to perform a dry-run without errors, even if no upgrade is necessary, it should still clear any error message on the HelmRelease resource.

**Comment by hiddeco** [comment]
@tommasopozzetti @carlpett can you please try out `hiddeco/helm-operator:release-reset-failure-c684c33b` and see if this results in the expected conditions?

**Comment by carlpett** [comment]
@hiddeco Yes, this seems to clear it for me. Thanks!

**Comment by tommasopozzetti** [comment]
@hiddeco Thanks for looking into this! A quick test of your change seems to fix the error for me as well.

**Comment by hiddeco** [comment]
Thank you both :tulip:
