### ISSUE TITLE
FAQ: Update

### ISSUE THREAD

**Issue by casibbald** [fluxcd/helm-operator#308]
FAQ Update:

`err="failed to upgrade chart for release [Release-Name]: rendered manifests contain a resource that already exists. Unable to continue with install: existing resource conflict: kind: Secret, namespace: default, name: flux-helm-repositories"`

When using Hierarchal chart dependencies, ensure that any CRD's or charts that are outside the template directories do not have names that conflict.

Chart 1 -> Depends on -> Chart 2

Chart 1:
crds/
  secret: blah

Chart 2:
crds/
  secret: blah

This scenario causes  a conflict due to crds not being templated and therefore care needs to be taken by the author to ensure that there are no conflicts:

Chart 1:
crds/
  secret: chart-1-blah

Chart 2:
crds/
  secret: chart-2-blah

**Comment by hiddeco** [comment]
The cause of this ended up being a duplicate resource in the used charts, and was not a Helm operator issue.
