### ISSUE TITLE
configureRepositories needs the same version check as other locations

### ISSUE THREAD

**Issue by kav** [fluxcd/helm-operator#310]
**Describe the bug**
configureRepositories needs the same helm3 treatment as the rest of the helm config and cache since they randomly moved the repository files as well.

**To Reproduce**
Steps to reproduce the behavior (using helm.versions=v3)

1. Setup a repositories.yaml file and private key as in: https://github.com/fluxcd/helm-operator/issues/17#issuecomment-586456020 (Also tweaking the locations to match helm3)
1. Notice it doesn't work:
` chart unavailable: looks like "<chart_repo>" is not a valid chart repository or cannot be reached: Get <chart_repo>/index.yaml: x509: certificate signed by unknown authority`
1. Shell into the container and note the repositories.yaml file isn't mounted at `/root/.config/helm/repositories.yaml` (the v3 location) but rather `/root/.helm/repository/repositories.yaml`

**Comment by kav** [comment]
Should be a very straightforward fix. I'll PR something in the AM

**Comment by hiddeco** [comment]
Ended up looking like a configuration and/or interpretation issue, see #311.

**Comment by kav** [comment]
It's still a bug, potentially "won't fix". If the chart repository is unreachable when the helm operator starts and you are using helm 3 the repositories entry for that repo won't be written correctly.

**Comment by kav** [comment]
Given the CRD coming down the pike this is probably not worth fixing. For my own use case; Helm Operator bringing up the chart repo it later uses, I can add a reboot the helm operator pod to work around
