### ISSUE TITLE
How clean up/deal with: "unable to sync release with status pending-upgrade"

### ISSUE THREAD

**Issue by bitsofinfo** [fluxcd/helm-operator#316]
```
ts=2020-02-22T17:38:25.85112908Z caller=release.go:347 component=release release=testapp targetNamespace=omg-apps resource=my-apps:helmrelease/testapp-5.0.4-1--1-1 helmVersion=v2 warning="unable to sync release with status pending-upgrade" action=skip
```

I have a helm release stuck in this state, any settings in the operator that can force smoke a stuck release like this when there is another pending that may fix it?

**Comment by DaemonDude23** [comment]
I've run into this too. This came up in the Slack channel today, and a Flux maintainer recommended to manually run the `helm upgrade` command like one would without Flux in the picture. I extracted the values from my `HelmRelease` file, and ran the upgrade myself, and then the `helm-operator` saw this and updated its status.

**Comment by hiddeco** [comment]
See https://docs.fluxcd.io/projects/helm-operator/en/latest/helmrelease-guide/reconciliation-and-upgrades/#upgrade-failures
