### ISSUE TITLE
Docs not working

### ISSUE THREAD

**Issue by ttarczynski** [fluxcd/helm-operator#320]
**Describe the bug**

When following the link https://docs.fluxcd.io/projects/helm-operator it returns HTTP 404
Took the link from the main project page: https://fluxcd.io/

**To Reproduce**

Steps to reproduce the behaviour:
1. Go to: https://docs.fluxcd.io/projects/helm-operator

**Expected behavior**

Docs available.

**Comment by hiddeco** [comment]
Has been resolved in https://github.com/fluxcd/flux/pull/2863 but our documentation is generated from the tagged release and thus static.

The version on https://docs.fluxcd.io/en/latest/ build from `master` does work.
