### ISSUE TITLE
Documented defaults for `createCRD` don't match actuals

### ISSUE THREAD

**Issue by dcherman** [fluxcd/helm-operator#34]
Hi,

The documented defaults for `createCRD` don't match what's in `values.yaml`

https://github.com/fluxcd/helm-operator/blob/6bfd9fa8a87f686ddbac8332ae5e1eb9cee6893e/chart/helm-operator/values.yaml#L13

https://github.com/fluxcd/helm-operator/blob/6bfd9fa8a87f686ddbac8332ae5e1eb9cee6893e/chart/helm-operator/README.md#configuration

Happy to make a PR correcting this, just need to know which value you intended to be the default

**Comment by stefanprodan** [comment]
The default should be set to `false`
