### ISSUE TITLE
[update helm version]

### ISSUE THREAD

**Issue by xriser** [fluxcd/helm-operator#345]
Please upgrade helm version in the helm operator container 3.0.3 -> 3.1.2

**Comment by hiddeco** [comment]
https://github.com/fluxcd/helm-operator/blob/master/docker/helm3.version#L1

**Comment by xriser** [comment]
I mean update the official image as well
https://github.com/fluxcd/helm-operator/blob/master/chart/helm-operator/values.yaml#L8
