### ISSUE TITLE
Upon chart install, CRD is always created.

### ISSUE THREAD

**Issue by juyttenh** [fluxcd/helm-operator#355]
**Describe the bug**
When installing the helm-operator chart, the CRD is always created although (according to documentation) by default createCRD=false. 
As a consequence, installing with createCRD=true fails with an existing resource conflict.

**To Reproduce**
0. Run the helm-operator install:
`helm upgrade -i helm-operator fluxcd/helm-operator --namespace flux --set helm.versions=v3`
Run `kubectl get crd` to see the CRD was created although it shouldn't have been.

1. Run helm-operator install with request to create the CRD:
`helm upgrade -i helm-operator fluxcd/helm-operator --namespace flux --set helm.versions=v3 --set createCRD=true`
Observe the error: 
`Error: rendered manifests contain a resource that already exists. Unable to continue with install: existing resource conflict: namespace: , name: helmreleases.helm.fluxcd.io, existing_kind: apiextensions.k8s.io/v1beta1, Kind=CustomResourceDefinition, new_kind: apiextensions.k8s.io/v1beta1, Kind=CustomResourceDefinition`

**Expected behavior**
As documented, CRD should only be created when installed with createCRD=true.

**Additional context**
Add any other context about the problem here, e.g 
- Helm Operator version: fluxcd/helm-operator:1.0.0-rc9
- Targeted Helm version: 3.2.1
- Kubernetes version: 1.17.3 (aks)
- Git provider: github
- Container registry provider: github

**Comment by hiddeco** [comment]
Try using `--skip-crds` for Helm 3.

**Comment by juyttenh** [comment]
Thanks, I can confirm adding `--skip-crds` solves the issue. Perhaps the readme/docs could use a little update for this case.

This leads to a somewhat strange behaviour though: with Helm 3 you'd always need to add this `--skip-crds` when you'd want to use the `createCRD` switch. But why would you use the latter anyways when you use Helm 3? It's a bit confusing. 
So as a small improvement I'd suggest keeping this `createCRD` switch available only for Helm 2 usage, since this `--skip-crds` Helm 3 option covers the same need?

**Comment by stefanprodan** [comment]
Yes the `createCRD` switch is intended for Helm v2 only, I agree we should update the chart readme and explain `--skip-crds` vs `createCRD`.
