### ISSUE TITLE
`helm test` integration

### ISSUE THREAD

**Issue by seaneagan** [fluxcd/helm-operator#369]
**Describe the feature**

An ability to declare for HelmReleases the intention to run the equivalent of `helm test` when deploying each new release revision.

**HelmRelease test key**

A new `test` key would be added to HelmRelease.

```yaml
  # Wait defaults to true if tests (or rollbacks) are enabled
  wait: true 
  test:
    # Default false (possibly change to true for v2 HelmRelease).
    enable: true 
```

The fate of any given test run will be determined solely by the associated [hook delete policy](https://helm.sh/docs/topics/charts_hooks/#hook-deletion-policies). So a test being interrupted by a new release revision or new test would be handled in the same way as if it had occurred via the Helm CLI.

**Statusing**

The HelmRelease status and [metrics](https://docs.fluxcd.io/projects/helm-operator/en/stable/references/monitoring/) would gain new phases named `Testing` and `TestFailed`. If `test.enable` is true, then the `Succeeded` phase and `Released` condition will now only be reached after tests succeed. If there were no helm tests defined by the chart, the release will still move to `Succeeded`, similarly to how `helm test` returns successfully in this case. One can continue to watch releases in the same way as before, with the exception of perhaps needing to account for the extra time it takes to run the tests:

```
kubectl wait --timeout 600s --for condition=released hr/prometheus
```

The HelmRelease status `test` key will additionally contain the test result as recorded in `helm status`. This will work in conjunction with the operator's --status-update-interval.

**Test Retries**

As of Helm 3, helm tests are Jobs which already have timeout and retry semantics, so there is already some ability for this built in. However, if one wants to manually force additional retries, one option is to run `helm test`, which will be detected by the operator's --status-update-interval functionality. They may not have access to do this though. So another option could be to add semantics to the operator, such that anytime the HelmRelease is updated, regardless of whether any release changes were found necessitating a new release revision, if the prior test failed, run the test again. In that case, one could force a test retry merely by updating an arbitrary metadata annotation on the HelmRelease.

**Non-gating tests (optional extension)**

It may be useful to run tests, but not gate the release on them. There could be a `test.gating` (or maybe `test.wait`) field, which defaults to true, but when set to false test success isn't required to mark the HelmRelease as `Released`, and test failure doesn't result in uninstalls/rollbacks/retries. In this case the testing status is merely exposed in `status.phase` (`Testing` or `TestFailed` as mentioned above) and in a new `Tested` condition which requires test success, and which exists regardless of whether the tests are gating, for consistency.

If there is interest in adding this feature, I would like to work on it.

**Comment by c4m4** [comment]
we need to use kubectl wait when we deploying one hr, because kubectl always return without check and fluxcd pass succeded to fluxcloud without waiting for the final result :(
