### ISSUE TITLE
Clarify meaning of metrics on monitoring.md

### ISSUE THREAD

**Issue by cep21** [fluxcd/helm-operator#381]
Hi,

I'm reading https://github.com/fluxcd/helm-operator/blob/master/docs/references/monitoring.md and the difference between release_phase_duration_seconds and release_duration_seconds isn't very clear to me.  The only difference seems to be "Release" and "Release Phase", which I'm not sure where they are defined.  Is it possible to add some clarification comments around how the two metrics are different?

Thanks!

**Comment by hiddeco** [comment]
A release consists of one or multiple phases.

The `*_release` is the total duration of the whole releases process, this includes all preparations and the one or many phases it goes through.

The `_*release_phase` is the duration of a single phase of type `x` for that release.
