### ISSUE TITLE
Error when deploying git's helm chart

### ISSUE THREAD

**Issue by yshcoffee2** [fluxcd/helm-operator#394]
**Describe the bug**
When the Helm release is applied, the following error occur and the install is impossible.
error="failed to prepare chart for release: chart not ready: no existing git mirror found"

It's the same if I try again and again.

**To Reproduce**
Steps to reproduce the behaviour:
0. install helm-operator 
helm upgrade -i helm-operator helm-operator --set helm.versions=v3 --namespace flux

1. create che namespace

2. apply helm release
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: che
  namespace: che
spec:
  releaseName: che
  targetNamespace: che
  timeout: 300
  resetValues: false
  wait: false
  forceUpgrade: false
  chart:
    git: https://github.com/eclipse/che.git
    ref: master
    path: deploy/kubernetes/helm/che
    skipDepUpdate: false
  values:
    global:
      cheWorkspacesNamespace: "che"
      ingressDomain: 172.22.11.15.nip.io

**Expected behavior**

**Logs**
[helm-operator install log]
#helm upgrade -i helm-operator helm-operator --set helm.versions=v3 --namespace flux
Release "helm-operator" does not exist. Installing it now.
NAME: helm-operator
LAST DEPLOYED: Wed Apr 29 02:41:30 2020
NAMESPACE: flux
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
Flux Helm Operator docs https://docs.fluxcd.io

Example:

AUTH_VALUES=$(cat <<-END
usePassword: true
password: "redis_pass"
usePasswordFile: true
END
)

kubectl create secret generic redis-auth --from-literal=values.yaml="$AUTH_VALUES"

cat <<EOF | kubectl apply -f -
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: redis
  namespace: default
spec:
  releaseName: redis
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com
    name: redis
    version: 9.0.2
  valuesFrom:
  - secretKeyRef:
      name: redis-auth
  values:
    master:
      persistence:
        enabled: false
    volumePermissions:
      enabled: true
    metrics:
      enabled: true
    cluster:
      enabled: false
EOF

watch kubectl get hr

[helm-operator log] : 
W0429 02:45:30.334637       6 client_config.go:543] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
ts=2020-04-29T02:45:30.33576631Z caller=operator.go:82 component=operator info="setting up event handlers"
ts=2020-04-29T02:45:30.335797467Z caller=operator.go:98 component=operator info="event handlers set up"
ts=2020-04-29T02:45:30.335817199Z caller=main.go:287 component=helm-operator info="waiting for informer caches to sync"
ts=2020-04-29T02:45:30.435967624Z caller=main.go:292 component=helm-operator info="informer caches synced"
ts=2020-04-29T02:45:30.436055055Z caller=operator.go:110 component=operator info="starting operator"
ts=2020-04-29T02:45:30.436534973Z caller=operator.go:112 component=operator info="starting workers"
ts=2020-04-29T02:45:30.436163021Z caller=git.go:104 component=gitchartsync info="starting sync of git chart sources"
ts=2020-04-29T02:45:30.436917261Z caller=server.go:42 component=daemonhttp info="starting HTTP server on :3030"
ts=2020-04-29T02:45:31.216270646Z caller=checkpoint.go:24 component=checkpoint msg="up to date" latest=0.10.1

< --------- apply helm release 
ts=2020-04-29T02:45:56.805096326Z caller=release.go:75 component=release release=che targetNamespace=che resource=che:helmrelease/che helmVersion=v3 info="starting sync run"
ts=2020-04-29T02:45:56.805132496Z caller=git.go:307 component=gitchartsync info="started mirroring new remote" remote=https://github.com/eclipse/che.git mirror=https://github.com/eclipse/che.git
ts=2020-04-29T02:45:56.814016027Z caller=release.go:81 component=release release=che targetNamespace=che resource=che:helmrelease/che helmVersion=v3 error="failed to prepare chart for release: chart not ready: no existing git mirror found"
------------ >
 

**Additional context**
[helm version]
version.BuildInfo{Version:"v3.2.0", GitCommit:"e11b7ce3b12db2941e90399e874513fbd24bcb71", GitTreeState:"clean", GoVersion:"go1.13.10"}

[helm operator version]
v1.0.1

[k8s version]
v1.17.2

**Comment by hiddeco** [comment]
The Helm Operator is likely unable to connect to `eclipse`, resolving this issue will result in the release getting installed.

**Comment by yshcoffee2** [comment]
[additional info]

ts=2020-04-29T02:45:56.814016027Z caller=release.go:81 component=release release=che targetNamespace=che resource=che:helmrelease/che helmVersion=v3 error="failed to prepare chart for release: chart not ready: no existing git mirror found"

----- After this error, the following error occurs as helm operator continues to retry.

ts=2020-04-29T08:31:13.023043805Z caller=release.go:75 component=release release=che targetNamespace=che resource=che:helmrelease/che helmVersion=v3 info="starting sync run"
ts=2020-04-29T08:31:13.026141942Z caller=release.go:81 component=release release=che targetNamespace=che resource=che:helmrelease/che helmVersion=v3 error="failed to prepare chart for release: chart not ready: git clone --mirror: running git command: git [clone --mirror https://github.com/eclipse/che.git /tmp/flux-gitclone453717047]: context deadline exceeded"
ts=2020-04-29T08:34:13.023074672Z caller=release.go:75 component=release release=che targetNamespace=che resource=che:helmrelease/che helmVersion=v3 info="starting sync run"
ts=2020-04-29T08:34:13.026262341Z caller=release.go:81 component=release release=che targetNamespace=che resource=che:helmrelease/che helmVersion=v3 error="failed to prepare chart for release: chart not ready: git clone --mirror: running git command: git [clone --mirror https://github.com/eclipse/che.git /tmp/flux-gitclone368048894]: context deadline exceeded"
ts=2020-04-29T08:37:13.023261673Z caller=release.go:75 component=release release=che targetNamespace=che resource=che:helmrelease/che helmVersion=v3 info="starting sync run"
ts=2020-04-29T08:37:13.027290858Z caller=release.go:81 component=release release=che targetNamespace=che resource=che:helmrelease/che helmVersion=v3 error="failed to prepare chart for release: chart not ready: git clone --mirror: running git command: git [clone --mirror https://github.com/eclipse/che.git /tmp/flux-gitclone206151497]: context deadline exceeded"

[To @hiddeco]
error message seem to unable to connect to eclispe. 

but when I aceessed to eclipse in helm operator, it worked well.

[Test]
root@node1:~# k exec -it helm-operator-5b788d7474-qv7xr -n flux sh
/home/flux # git clone --mirror https://github.com/eclipse/che.git /tmp/flux-gitclone206151497
Cloning into bare repository '/tmp/flux-gitclone206151497'...
remote: Enumerating objects: 17, done.
remote: Counting objects: 100% (17/17), done.
remote: Compressing objects: 100% (16/16), done.
remote: Total 872860 (delta 7), reused 3 (delta 1), pack-reused 872843
Receiving objects: 100% (872860/872860), 246.08 MiB | 17.36 MiB/s, done.
Resolving deltas: 100% (359395/359395), done.
/home/flux # ls /tmp
flux-gitclone206151497


What can I do to solve the problem?

**Comment by hiddeco** [comment]
`Receiving objects: 100% (872860/872860), 246.08 MiB | 17.36 MiB/s, done.`

The size of the repository is likely too large to complete the initial clone within the default `--git-timeout` of `30s`. Given the size however and most of the contents of the repository being unrelated to the chart, I would advice to not make use of a Git repository but use a published chart from a Helm repository if available.

**Comment by alesabater** [comment]
That fixed the issue for me @hiddeco. In my case I was having the exact same issue by using the official source for helm charts https://github.com/helm/charts. 

I didn't find the log **"no existing git mirror found"** when debugging the issue. A hint to the --git-timeout flag could be useful.  

I used `--git-timeout=2m`.

**Comment by hiddeco** [comment]
Glad you got it resolved! I would however (again) discourage you from using repositories of this size for a single chart.

**Comment by yshcoffee2** [comment]
@alesabater @hiddeco  Thank you very much~! I changed default git-timeout value and installed it, and it works fine :)

**Comment by GlorifiedTypist** [comment]
Not a helm-operator issue, but may help somebody who has error="failed to prepare chart for release: chart not ready: no existing git mirror found" but is not related to git timeout.

I got the same `error="failed to prepare chart for release: chart not ready: no existing git mirror found"`. In my case gatekeeper was blocking the release.

`Warning  FailedCreate  4m3s (x17 over 9m31s)  replicaset-controller  Error creating: admission webhook "validation.gatekeeper.sh" denied the request: [denied by k8s-resource-limits] container <dev-app> has no CPU and memory resource limits are not defined`

helm-operator did not feed this infomation back to me for the replicaset, instead it "timedout". Removing the gatekeeper sorted this out for me.
