### ISSUE TITLE
Release condition gauge (instead of phase gauge)

### ISSUE THREAD

**Issue by seaneagan** [fluxcd/helm-operator#395]
**Describe the feature**

The release phase gauge added in #383 exposes phases, which are a [deprecated concept](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#typical-status-properties) in the kubernetes API conventions, due to backward compatibility issues. For example adding new phases would make the metric integer values associated with each phase difficult to assign appropriately. Thus it may be better to expose a conditions based gauge rather than a phased based one.

The gauge could be called `release_condition_info` and have labels for `namespace`, `release_name`, and `condition_type`, and values could be something like -1 (false), 0 (unknown or condition absent), 1 (true).

**Comment by seaneagan** [comment]
Also at this point in time the phase gauge hasn't made it into a release, so if this issue is accepted perhaps removing the phase gauge should be release blocking.

**Comment by sa-spag** [comment]
Good point, it also questions the use of phases as a whole, which was introduced with #334. Nonetheless I am not familiar with the differences between the concept of condition and phase, what it implies for the Helm Operator why conditions were not chosen as a solution to the initial observability issue.

As far as I'm concerned, seems like the list of available conditions mostly covers what phase exposes but transition states, which are not very useful in terms of alerting.
