### ISSUE TITLE
OwnerReferences on created resources

### ISSUE THREAD

**Issue by michaelgeorgeattard** [fluxcd/helm-operator#398]
Would it be possible to add `ownerReferences` to created resources to link these resources with the `HelmRelease` custom resource that created them?

This would allow tools such as ArgoCD to show resource links in the UI.

**Comment by hiddeco** [comment]
Not possible as an owner reference needs to refer to a resource in the same namespace and both Helm and the operator itself allow managing and creating releases and/or resources in any namespace (and the link can thus not be made).

**Comment by ooneko** [comment]
Is it possible to use a "cluster level CRD" to  represent a Helm Release?
Set ownerReference to it, it will delete any parts of  the release, when delete the release.
