### ISSUE TITLE
Support for pre-update replicas adjustment with HelmRelease

### ISSUE THREAD

**Issue by cf-sewe** [fluxcd/helm-operator#418]
**Describe the feature**
I have a helm chart for an application (StatefulSet) which needs adjusting replicas to 1 before updating (Database migrations):
```
helm upgrade myapp oldchart --set replicaCount=1 --reuse-values
helm upgrade myapp newchart
helm upgrade myapp newchart --set replicaCount=3 --reuse-values
```

Could this procedure be automated with HelmRelease? Is there an alternative approach which fits the GitOps/Helm Operator approach?

**What would the new user story look like?**
How would the new interaction with the Helm Operator look like? E.g.
1. HelmRelease defines to adjust replicas to 1 before update
2. A new `HelmRelease` is applied
3. Deployment is triggered and adjusts the replicas of the deployment or StatefulSet to 1 
4. When done, replicas is adjusted to previous value.

**Expected behaviour**
When flux updates the HelmRelease with a new docker image tag or changes the helm chart version, the Helm Operator should adjust the replicas of the StatefulSet (or Deployment) down to one. Then it would apply the update. At the end, it would scale the replicas back to the original value.

**Comment by seaneagan** [comment]
Can you use a `pre-upgrade` helm hook to implement that?

https://helm.sh/docs/topics/charts_hooks

**Comment by sweitzel** [comment]
Thanks for your tip - I haven't thought of that possibility. 
The chart is under our control, so that could be a proper solution. 

You can close this request. If you think it might still be a worthwhile feature for Helm Operator, feel free to leave it open :-)

**Comment by cf-sewe** [comment]
Thanks for your tip - I haven't thought of that possibility.
The chart is under our control, so that could be a proper solution.

I am therefore closing  this request. If you think it might still be a worthwhile feature for Helm Operator, feel free to reopen :-)
