### ISSUE TITLE
Helm chart version need to be update

### ISSUE THREAD

**Issue by tux-00** [fluxcd/helm-operator#428]
**Describe the bug**

+ Image tag of helm operator chart has been updated but the the chart version has not.

+ the changelog of helm chart is missing the 1.0.2 version

**To Reproduce**

Steps to reproduce the behaviour:
1. helm repo update
2. helm fetch fluxcd/helm-operator
3. vim values.yaml

**Expected behavior**

When fetching last version of chart, the default values need to use helm operator v1.1.0.

**Comment by hmoravec** [comment]
I was also scratching my head why I get this error  #423 even in version 1.1.0 where it should be fixed. The chart and image versions are correct in this repo but the Helm package has wrong image version.

It seems the chart version was bumped to 1.0.2 on 6.5. without updating the image version. The image version was fixed on 21.5. but it did not pass the build: https://github.com/fluxcd/helm-operator/commits/master/chart/helm-operator/Chart.yaml

**Comment by hiddeco** [comment]
New chart was just released.
