### ISSUE TITLE
Let flux deploy a bundle of helmreleases

### ISSUE THREAD

**Issue by timokorny** [fluxcd/helm-operator#43]
Hi,

not sure if i am right here.
I have the question if the flux operator is able to deploy a bundle of helmreleases via another helmrelease.
I defined helmreleases for several services and want to deploy them as a bundle of services.
Is that already possible and if so, how is that working/should the "master-helmrelease" look like?

Thanks in advance and best regards
timokorny

**Comment by hiddeco** [comment]
I would advice you to bundle the underlying charts in an [umbrella chart](https://helm.sh/docs/developing_charts/#complex-charts-with-many-dependencies) so that you can manage them through one `HelmRelease`.

**Comment by timokorny** [comment]
Ok, i will try that.
Thanks for replying that fast!
