### ISSUE TITLE
"Synchronization of release X failed: release appears to be managed by Y" if multiple resources are in the same namespace

### ISSUE THREAD

**Issue by Klohto** [fluxcd/helm-operator#443]
**Describe the bug**

Hello!
We are running into an issue when syncing multiple HelmReleases targetting the same namespace.
For example, we have
* dwh-query-service-kij2ab service in dwh-query namespace
* dwh-query-service-st8kwe service in dwh-query namespace

On syncing, helm-operator will report
`synchronization of release 'can-docker-dwh-query-service-kij2ab' in namespace 'can-docker-dwh-query-service-staging' failed: failed to determine sync action for release: release appears to be managed by 'can-docker-dwh-query-service-staging:helmrelease/can-docker-dwh-query-service-st8kwe'`

I narrowed it into an issue in **managedByHelmRelease** function, where the looping over resources in the same namespace happens and returns the result for the **first** resource in the loop.
https://github.com/fluxcd/helm-operator/blob/706bcb34841ed65fed007ad706082f28429e19bb/pkg/release/annotator.go#L26-L57

Thankfully namespacedResourceMap returns a map, so this isn't blocking error and the resource will eventually sync once it hits a correct source release.

**Expected behavior**

managedByHelmRelease will sync a correct HelmResource on a first try without complaining

**Additional context**

- Helm Operator version: 1.1.0
- Kubernetes version: 1.14.9

**Comment by hiddeco** [comment]
I am not sure this is because multiple resources exist in the same namespace, but find it more likely it is because your releases (or charts) manage the same resource. As only the annotations of the resources listed by the metadata for the Helm release are checked and annotated (see logic in ` releaseManifestToUnstructured` and `namespacedResourceMap`).

**Comment by Klohto** [comment]
Both are annotated fully, including their IDs:  
`helm.fluxcd.io/antecedent: can-docker-dwh-cache-service-staging:helmrelease/can-docker-dwh-cache-service-kij2ab`
In that case, it would be a problem with parsing and the resources would never sync. In my case, they sync on random occasions and reference the other HelmRelease in the error log.

**Comment by Klohto** [comment]
I see what do you mean now.
So the issue is in an incorrect Helm deployment getting mapped together with a wrong HelmRelease

Which would be here, right?
https://github.com/fluxcd/helm-operator/blob/706bcb34841ed65fed007ad706082f28429e19bb/pkg/release/release.go#L185

**Comment by Klohto** [comment]
Just thinking aloud here. (No way how to debug it on my side though).

Assuming the wrong curRel is retrieved it might be related to our HelmRelease spec, because we don't use releaseName but only name.

GetReleaseName then returns a name in a format "namespace-name" instead just "relaseName".
This is then passed to Helm client which retrieves a wrong release.
Doesn't explain how come it sometimes syncs.

**Comment by hiddeco** [comment]
Can you provide me with an (anonymized) version of both `HelmRelease` resources so I can get a full picture?

**Comment by Klohto** [comment]
We finished this convo on Slack, Hidde was a great help!

To summarize:
- HelmReleases were valid but the syncing problem wasn't with the HR per se, but with the created resources based on our Chart template.
- We were using (creating) one ServiceAccount for both services
- Every other resource is synced except for ServiceAccount, where the conflict was

This doesn't go well with the GitOps approach, so you can either sync SA with Flux and disable creating of SA in each HelmRelease, that way it won't be managed by that HR.
Or you can create separate SA for each HR.
