### ISSUE TITLE
helm release resource annotation "fluxcd.io/ignore" not getting changed even if the git repo is updated

### ISSUE THREAD

**Issue by vishalcs05** [fluxcd/helm-operator#450]
**Describe the bug**

While creating helm release I set "fluxcd.io/ignore: false" annotation in git repo flux file but when its changed to "fluxcd.io/ignore: true", helmrelease object still shows "fluxcd.io/ignore: false"

**To Reproduce**

Steps to reproduce the behaviour:
1. Create a release in git with annotation "fluxcd.io/ignore: false"
2. Once the release is deployed, make change in git and set "fluxcd.io/ignore: true"
3. helmrelease resource on the cluster will not be changed and it will still show "fluxcd.io/ignore:" annotation as "false" even though it has been set to "true" in steps 2.

**Expected behavior**

Expect hr resource to also set annotation to "fluxcd.io/ignore: true" once updated in git file.

**Additional context**

- Helm Operator version: 1.1.0
- Kubernetes version: v1.13.10
- Git provider: gitlab
- Helm repository provider: gitlab

**Comment by ttarczynski** [comment]
@vishalcs05  I think what you described is the intended behaviour of flux.
See the docs here: https://docs.fluxcd.io/en/1.20.2/faq/#can-i-temporarily-make-flux-ignore-a-manifest
```
Flux will ignore any resource that has the annotation either in git, or in the cluster 
itself; sometimes it may be easier to annotate a running resource in the cluster 
as opposed to committing a change to git.
```
To me it means that when you set `fluxcd.io/ignore: true` it tells flux to ignore this manifest and not to do any changes in the cluster. So it will not change this annotation value in the cluster.

**Comment by vishalcs05** [comment]
thanks @ttarczynski for answering the query.
