### ISSUE TITLE
Rollback Timeout Not Respected

### ISSUE THREAD

**Issue by stevenpall** [fluxcd/helm-operator#510]
**Describe the bug**

It appears that despite `spec.rollback.timeout` being set to a non-default value, rollbacks will still occur after 300s.

**To Reproduce**

Steps to reproduce the behaviour:
**1.** Install Helm Operator via Helm
**2.** Add a `HelmRelease` with rollback enabled and non-default rollback timeout value, e.g.:
```
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: test
  namespace: test
spec:
  chart:
    git: ssh://git@github.com/test/flux-configs
    ref: master
    path: charts/test
  releaseName: test
  rollback:
    enable: true
    wait: true
    timeout: 600
    disableHooks: true
  values: {}
```
The issue can only be reproduced if the rollout takes more than 300s (if there are a lot of pods associated with the deployment, pods take a while to shut down and start up, etc.)
**3.** Initiate a new release by updating a component of the `HelmRelease`
**4.** Wait 300s and observe that the release gets rolled back despite the higher timeout value set in `spec.rollback.timeout`.

**Expected behavior**

The operator should wait up until the specified timeout to initiate a rollback.

**Logs**

```
Aug 04 08:01:16 flux-helm-operator ts=2020-08-04T15:01:16.372697643Z caller=release.go:353 component=release release=test targetNamespace=test resource=test:helmrelease/test helmVersion=v2 info="running upgrade" action=upgrade
Aug 04 08:06:22 flux-helm-operator ts=2020-08-04T15:06:22.648885177Z caller=release.go:357 component=release release=test targetNamespace=test resource=test:helmrelease/test helmVersion=v2 error="upgrade failed: timed out waiting for the condition" action=upgrade
Aug 04 08:06:23 flux-helm-operator ts=2020-08-04T15:06:23.333202885Z caller=release.go:409 component=release release=test targetNamespace=test resource=test:helmrelease/test helmVersion=v2 info="running rollback" phase=rollback
```

**Additional context**

- Helm Operator version: `1.2.0`
- Kubernetes version: `1.15`
- Git provider: GitHub
- Helm repository provider: N/A (charts hosted in repo)

**Comment by sa-spag** [comment]
You should set `.spec.timeout`. From [the documentation](https://docs.fluxcd.io/projects/helm-operator/en/stable/references/helmrelease-custom-resource/#helm.fluxcd.io/v1.HelmRelease):
> Timeout is the time to wait for any individual Kubernetes operation (like Jobs for hooks) **during installation and upgrade operations**.

Whereas `.spec.rollback.timeout`:
> Timeout is the time to wait for any individual Kubernetes operation (like Jobs for hooks) **during rollback**.

**Comment by stevenpall** [comment]
Ah, makes sense. I must have misunderstood!
