### ISSUE TITLE
Versioned kubernetes client does not compile

### ISSUE THREAD

**Issue by tanelso2** [fluxcd/helm-operator#520]
**Describe the bug**
I was attempting to write a project in Golang that would create a new HelmRelease when an endpoint was called.

However, I cannot use the clientset package included in this repo, as it fails to compile with:

```
 /go/src/github.com/fluxcd/helm-operator/pkg/client/clientset/versioned/typed/helm.fluxcd.io/v1/helmrelease.go:74:5: not enough arguments in call to c.client.Get().Namespace(c.ns).Resource("helmreleases").Name(name).VersionedParams(&options, scheme.ParameterCodec).Do
 	have ()
 	want (context.Context)
```

This section of the code looks like it was auto-generated, so possibly it needs to be generated again?

**Comment by hiddeco** [comment]
You are likely using `v0.18.x` Kubernetes dependencies in your project, while the Helm Operator uses `v0.17.x` dependencies as this is required for Helm 2 to work.

https://github.com/fluxcd/helm-operator/blob/master/go.mod#L33-L37

**Comment by tanelso2** [comment]
Ok thank you, that's helpful. However, I'm having another problem installing this package now with go modules (and I am very inexperienced with them)

```bash
$ go get -u github.com/fluxcd/helm-operator@v1.2.0
go get: github.com/fluxcd/helm-operator@v1.2.0 requires
	github.com/fluxcd/helm-operator/pkg/install@v0.0.0-00010101000000-000000000000: invalid version: unknown revision 000000000000
```

Do you have any idea how to resolve this?

Are there any example projects using this package that I can look at for reference?
