### ISSUE TITLE
How to make sure dependent resources are present before a chart is getting installed

### ISSUE THREAD

**Issue by renypaul** [fluxcd/helm-operator#530]
I have a use case where my application container need a database container and I have some migrations configured as a helm jobs. How can I make sure that the database is installed and up before the application charts gets installed ?

**Comment by stefanprodan** [comment]
This has been implemented in helm-controller. You can define the db HelmRelease as a dependency for the app chart https://toolkit.fluxcd.io/components/helm/helmreleases/#helmrelease-dependencies
