### ISSUE TITLE
Support Helms --no-hooks  Flag

### ISSUE THREAD

**Issue by kferrone** [fluxcd/helm-operator#531]
**Describe the feature**
I would like to skip on the hooks in the helm chart by using `--no-hooks `

I imagine:

```yaml
spec:
  noHooks: true
```

**Comment by paolomainardi** [comment]
@kferrone so why using helm ? it would be the same to generate templates and apply them as is.

**Comment by kingdonb** [comment]
Hopefully you have moved onto Helm Controller. It looks like `disableHooks` was implemented on Helm Controller as separate configuration directives on [Install, uninstall, rollback, and upgrade](https://fluxcd.io/docs/components/helm/api/#helm.toolkit.fluxcd.io/v2beta1.Install) where you can control the behavior.

Sorry for the trouble, this **is** a supported feature in the current version of Flux.
