### ISSUE TITLE
Function 'htpasswd' not defined.

### ISSUE THREAD

**Issue by boxcee** [fluxcd/helm-operator#535]
**Describe the bug**
Installing a chart which uses 'htpasswd' function fails.

**To Reproduce**
Steps to reproduce the behaviour:
1. Install helm locally (v3.3.3).
2. Create helm chart locally.
3. Modify `templates/_helpers.tpl`.
4. Add section:
```
{{- define "auth.username" -}}
{{- default "username" .Values.ingress.auth.username }}
{{- end }}
{{- define "auth.password" -}}
{{ default (randAlphaNum 25) .Values.ingress.auth.password }}
{{- end }}
{{- define "auth.credentials" -}}
{{ htpasswd (include "auth.username" .) (include "auth.password" .) }}
{{- end }}
```
5. Run `helm template` and test chart -> success.
6. Package and publish chart.
7. Try to install using `fluxcd` and `helm-operator`.

**Expected behavior**
Chart will be installed without problems.

**Logs**
```
ts=2020-09-22T12:58:55.650240388Z caller=helm.go:69 component=helm version=v3 info="preparing upgrade for mychart" targetNamespace=dev release=mychart
ts=2020-09-22T12:58:55.659981376Z caller=helm.go:69 component=helm version=v3 info="resetting values to the chart's original version" targetNamespace=dev release=mychart
ts=2020-09-22T12:58:55.73385416Z caller=release.go:294 component=release release=mychart targetNamespace=dev resource=dev:helmrelease/mychart helmVersion=v3 error="dry-run upgrade for comparison failed: parse error at (mychart/templates/_helpers.tpl:88): function \"htpasswd\" not defined" phase=dry-run-compare
```
**Additional context**
Add any other context about the problem here, e.g 
- Helm Operator version: helm-operator-1.2.0
- Targeted Helm version: v3
- Kubernetes version: 1.16
- Git provider: github.com
- Container registry provider: gcr.io

EDIT: `htpasswd` is documented here: https://helm.sh/docs/chart_template_guide/function_list/#htpasswd.

**Comment by hiddeco** [comment]
This is not a bug as the `htpasswd` function from Spring was introduced in Helm `v3.2.0-rc.1` and the Helm Operator currently relies on Helm `v3.1.x` (and will continue to, due to client compatibility issues between Helm `v2` and `v3`).

The [helm-controller](https://github.com/fluxcd/helm-controller) is running `v.3.3.3` and will/does support this function.
