### ISSUE TITLE
Alerts

### ISSUE THREAD

**Issue by kolesnikovIV** [fluxcd/helm-operator#540]
just looking at helm-controller as flux component and there some kind of integrations with notification-controller exists, any chance to use helm-operator + notification controller ?

**Comment by hiddeco** [comment]
No, the helm-controller is a replacement for the Helm Operator, and the notification-controller is specifically designed and build for integrations with GitOps Toolkit components. Given this, the Helm Operator does not work with it, nor are we planning to add support for it.
