### ISSUE TITLE
Upgrade Helm Version (cert-manager)

### ISSUE THREAD

**Issue by RichiCoder1** [fluxcd/helm-operator#545]
**Describe the bug**

Helm Operator will hang and fail when upgrading the `cert-manager` chart with the `installCRDs` flag set due to a bug fixed in Helm v3.3.1.
Details Here: https://cert-manager.io/docs/installation/upgrading/upgrading-0.15-0.16/

**To Reproduce**

```diff
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: kube-services
spec:
  releaseName: cert-manager
  chart:
    repository: https://charts.jetstack.io
    name: cert-manager
-    version: v0.15.0
+    version: v0.16.1
  values:
    installCRDs: true
```

**Expected behavior**

The chart is upgraded without issue.

**Comment by hiddeco** [comment]
We are currently stuck on `3.1.x`, see: https://github.com/fluxcd/helm-operator/pull/514#issuecomment-688166731.
