### ISSUE TITLE
Helm Operator (v1) is in maintenance mode

### ISSUE THREAD

**Issue by hiddeco** [fluxcd/helm-operator#546]
The Helm Operator (and Flux v1) are in maintenance mode and effectively have been for a while.

This means we

* are focusing all of our attention on [v2](https://toolkit.fluxcd.io) and
* will only be working on the Helm Operator (and Flux v1) for critical updates and bug fixes

If you are considering helping out with maintenance, please talk to us. We want to make this transition work for everyone.

### Why is this important?

We as a community decided we will invest into the future of GitOps by re-architecting our tooling from the ground up, resulting in

* Easier code
* Better observability
* Ease of integrating
* Composability and extensibility

The effort is well-underway and v2 is already on feature-parity in terms of Flux read-only mode and Helm Operator functionality. (And there’s already loads more in terms of functionality that Flux v1 and friends couldn't do, such as multiple repository support, health assessment of the deployed workloads, structured logging, events and alerts.)

Check out the guide on https://toolkit.fluxcd.io/guides/helmreleases/ to find out how to get started with the [helm-controller](https://github.com/fluxcd/helm-controller).

### Timeline

Please take a look at [the roadmap for Flux v2](https://toolkit.fluxcd.io/roadmap/). Once we have reached feature-parity across all current feature sets (➊ read-only mode, ➋ helm-operator, ➌ write operations), we will continue to support Flux v1 and Helm Operator v1 for 6 more months.

### I need help with an issue now

The Helm Operator is still being maintained and supported, it will just take a bit longer until we get around to issues and PRs. Critical bug fixes have our priority, we are going to be hesitant and look very careful at anything that will extend functionality.

First and foremost, you can help by checking out 
https://docs.fluxcd.io/projects/helm-operator/en/stable/troubleshooting/ and https://docs.fluxcd.io/projects/helm-operator/en/stable/faq/ very closely and asking for help on `#flux` on [CNCF Slack](https://slack.cncf.io) if necessary.

This is a very important transition period for us as a community, and we firmly believe that we'll come out stronger together on the other side. :rocket:

**Comment by stuartpb** [comment]
How do I install just the HelmController? The [documentation](https://toolkit.fluxcd.io/guides/installation/) only describes how to install some GitOps Toolkit thing that apparently needs its own binary. I don't need GitOps, just Helm.

**Comment by hiddeco** [comment]
@stuartpb the releases have a `.yaml` file attached to them with the bare minimum that is required to deploy the release: https://github.com/fluxcd/helm-controller/releases. Documentation around "standalone" installations will follow in the foreseeable future.

For further questions, please either [join the discussion](https://github.com/fluxcd/toolkit/discussions) or file an issue in the helm-controller repository.

**Comment by rafaelgaspar** [comment]
Flux is also in maintenance mode and still got `kubectl` binaries updated, any reason why with `helm` binary this is not the case? Any known breaking change?

**Comment by hiddeco** [comment]
@rafaelgaspar see:

- https://github.com/fluxcd/helm-operator/pull/514#issuecomment-688166731
- https://github.com/fluxcd/helm-operator/pull/514#issuecomment-743122502
