### ISSUE TITLE
Is able to disable reconciliation ? 

### ISSUE THREAD

**Issue by shiyuan-extreme** [fluxcd/helm-operator#555]
As the document said,  all HelmRelease resources are also queued for reconciliation every 3 minutes. Is there a way to disable this behavior ? 

> On the creation and update of a HelmRelease the resource is queued for reconciliation. Besides this all HelmRelease resources handled by the Helm operator instance are also queued for reconciliation every --charts-sync-interval (defaults to 3 minutes).

**Comment by Scong** [comment]
I've also been looking for a way to do this. I got some response on this from the flux slack channel.

https://cloud-native.slack.com/archives/CLAJ40HV3/p1604345135295400

Generally it is sounding like a 'No' not until v2.

**Comment by kingdonb** [comment]
You can disable reconciliation for individual HelmReleases in Flux v2, with `flux suspend helmrelease <foo>`

This was not possible in Flux v1 or Helm Operator.

You can also block individual resources from being reconciled away by Kustomize controller by applying an annotation:

```
kubectl annotate service/podinfo kustomize.toolkit.fluxcd.io/reconcile=disabled
```

I don't think that Helm Controller honors that annotation too (as Helm would have to honor it, I think...) but as I don't think that's what was being asked for anymore, I'm going to go ahead and slink away while I close this issue out. 👋
