### ISSUE TITLE
Examples and specifications of annotations do not match

### ISSUE THREAD

**Issue by derrickburns** [fluxcd/helm-operator#57]
https://github.com/fluxcd/flux/blob/7fd090af0dd9b63acc9fa1c8616d5bf5657c6160/docs/references/helm-operator-integration.md

Your examples do not meet your specification.

The keys you use for annotation examples do NOT match the keys you define in the examples. It is not clear which is correct.

It seems like this document is a mix of the old format and the new one.

**Comment by hiddeco** [comment]
They are both correct as we maintain support for the older ones until the next major version Flux. This has however been taken care of in https://github.com/fluxcd/flux/pull/2670.
