### ISSUE TITLE
Possible memory leak

### ISSUE THREAD

**Issue by BitProcessor** [fluxcd/helm-operator#582]
Hi,

I was looking at my `flux` namespace today to follow along a Helm release when I noticed the memory usage of the helm -operator container, roughly 2GB of RAM !

![Screenshot 2021-02-02 at 13 38 53](https://user-images.githubusercontent.com/50638541/106601841-6e7cc780-655c-11eb-87ba-adf65f4de567.png)

Could this be a memory leak somewhere? I'm running version 1.2.0

**Comment by BitProcessor** [comment]
Update, checked on 2 other k8s clusters, found one using 1.5GB of RAM (91d up) and one using about 650MB of RAM (82d up). Seems related to https://github.com/fluxcd/helm-operator/issues/427 at first sight?

**Comment by pjbgf** [comment]
Processing helm charts can be a resource intensive operation. Given that this project is now in "Migration and security support only", it is unlikely that any performance/resource consumption improvements will be merged.

For better resource optimisation you are better off migrating to Flux 2 and using [helm-controller](https://github.com/fluxcd/helm-controller/) instead. That new controller has a caching feature which decreases the resource consumption throughout of its lifecycle.

More information about the Flux 2 transition timetable can be found at: https://fluxcd.io/docs/migration/timetable/.
