### ISSUE TITLE
Support for CronJob

### ISSUE THREAD

**Issue by DeepakArora76** [fluxcd/helm-operator#601]
Please treat this bug as a support request/help/advice.

I am struggling to compose YAML which could be used to run cronjob. I came across issue #208 which shows an example of using CronJob and that is good. What I am not finding is how to schedule such cronjobs like "schedule: "0 1 * * *".

I appreciate if you could present a complete example of scheduling cronjobs in YAML.

And how could one supply command-line arguments as well to such cronjobs?

**Comment by kingdonb** [comment]
I'm not understanding how this is an issue for Helm Operator. This is not the appropriate place for support requests unless they are related to Helm Operator.

Sorry if there has been some confusion.
