### ISSUE TITLE
Upgrade helm lib to fix null value overrides

### ISSUE THREAD

**Issue by stevo-f3** [fluxcd/helm-operator#602]
**Describe the bug**

**To Reproduce**

Steps to reproduce the behaviour:
1. Provide the Helm Operator install instructions
2. Provide a HelmRelease example
3. Post the HelmRelease status, you can get this by running `kubectl describe helmrelease <name>`

**Expected behavior**

helm-operator uses outdated helm with a bug https://github.com/fluxcd/helm-operator/blob/master/go.mod#L32
The bug was fixed in helm https://github.com/helm/helm/pull/7743

**Logs**

If applicable, please provide logs. In a standard stand-alone installation, you'd get this by running `kubectl logs deploy/flux-helm-operator -n fluxcd`.

**Additional context**

- Helm Operator version: 1.2.0
- Kubernetes version: 1.19
- Git provider: GitHub
- Helm repository provider: GitHub

**Comment by stefanprodan** [comment]
We can't update the helm packages as they come with breaking changes due to Kubernetes client-go. Please consider moving to Flux v2 as helm-operator is deprecated and it will be archived soon, see https://fluxcd.io/docs/migration/helm-operator-migration/
