### ISSUE TITLE
Recommendations for alerting on failed releases

### ISSUE THREAD

**Issue by chainlink** [fluxcd/helm-operator#62]
I'd like to be able to alert on failed releases. I looked into hooking into the kubernetes events that the operator emits, but the only event emitted is `chartsynced` and it doesn't contain any error information.

```
Object:  { kind: 'Event',
  apiVersion: 'v1',
  metadata:
   { name: 'bad-hr-test.15cada07d1ccac62',
     namespace: 'new-ns',
     selfLink:
      '/api/v1/namespaces/new-ns/events/bad-hr-test.15cada07d1ccac62',
     uid: '507be1a7-e7ae-11e9-9058-42010a8000c0',
     resourceVersion: '1006825',
     creationTimestamp: '2019-10-05T20:25:47Z' },
  involvedObject:
   { kind: 'HelmRelease',
     namespace: 'new-ns',
     name: 'bad-hr-test',
     uid: '5077e09e-e7ae-11e9-9058-42010a8000c0',
     apiVersion: 'flux.weave.works/v1beta1',
     resourceVersion: '39704805' },
  reason: 'ChartSynced',
  message: 'Chart managed by HelmRelease processed',
  source: { component: 'helm-operator' },
  firstTimestamp: '2019-10-05T20:25:47Z',
  lastTimestamp: '2019-10-05T20:35:31Z',
  count: 7,
  type: 'Normal',
  eventTime: null,
  reportingComponent: '',
  reportingInstance: '' }
```

The only way I've found to discover bad releases is by introspecting the logs of the helm-operator. For example:
```
ts=2019-10-05T20:30:13.497815163Z caller=release.go:208 component=release error="Chart release failed: bad-hr-test: &status.statusError{Code:2, Message:\"render error in \\\"blah/templates/ui/deployment.yaml\\\": template: blah/templates/ui/deployment.yaml:21:55: executing \\\"blah/templates/ui/deployment.yaml\\\" at <required \\\"ui image tag required\\\" .Values.ui.image.tag>: error calling required: ui image tag required\", Details:[]*any.Any(nil), XXX_NoUnkeyedLiteral:struct {}{}, XXX_unrecognized:[]uint8(nil), XXX_sizecache:0}"
```

This sometimes appears the Status of the helm release, but it looks like sometimes isn't reported:

```
Name:         bad-hr-test
Namespace:    new-ns
Labels:       <none>
Annotations:  flux.weave.works/automated: false
              kubectl.kubernetes.io/last-applied-configuration:
                {"apiVersion":"flux.weave.works/v1beta1","kind":"HelmRelease","metadata":{"annotations":{"flux.weave.works/automated":"false"},"name":"bad...
API Version:  flux.weave.works/v1beta1
Kind:         HelmRelease
Metadata:
  Creation Timestamp:  2019-10-05T20:25:47Z
  Generation:          1
  Resource Version:    39705744
  Self Link:           /apis/flux.weave.works/v1beta1/namespaces/new-ns/helmreleases/bad-hr-test
  UID:                 5077e09e-e7ae-11e9-9058-42010a8000c0
Spec:
  Chart:
    Git:         git@github.com:something/cluster-config
    Path:        charts/blah
  Release Name:  bad-hr-test
Status:
  Conditions:
    Last Transition Time:  2019-10-05T20:30:08Z
    Message:               successfully cloned git repo
    Reason:                GitRepoCloned
    Status:                True
    Type:                  ChartFetched
    Last Transition Time:  2019-10-05T20:30:13Z
    Message:               rpc error: code = Unknown desc = release: "bad-hr-test" not found
    Reason:                HelmInstallFailed
    Status:                False
    Type:                  Released
```

I can think of a couple of different ways this might get solved:
- Publishing more kubernetes events 
- adding a `failed install` status to `release status` (currently it will only report a status if the install actually happened, not if there's a render issue)

If you're in favour of adding more kube events, how best should I add the eventBroader to the release.go and other helm related files?

Thanks!

-Kyle

**Comment by benhartley** [comment]
[`helm-exporter`](https://github.com/sstarcher/helm-exporter) can be useful here

**Comment by sa-spag** [comment]
Having the same concerns here. I am currently relying on a not so elegant Prometheus query:
```
sum(
  max_over_time(max(timestamp(changes(flux_helm_operator_release_duration_seconds_count{exported_namespace=~"$namespace", release_name=~"$release", success="true"}[30s]) > 0)) by (exported_namespace, release_name, success) [1d:1s])
  or
  -max_over_time(max(timestamp(changes(flux_helm_operator_release_duration_seconds_count{exported_namespace=~"$namespace", release_name=~"$release", success="false"}[30s]) > 0)) by (exported_namespace, release_name, success) [1d:1s])
) by (exported_namespace, release_name)
```
It basically computes the difference between the timestamp of the last successful sync and the timestamp of the last failed sync (using `changes` to detect syncs).

As stated by @chainlink, new events would be very handy (e.g. using  events for [these conditions](https://github.com/fluxcd/helm-operator/blob/master/pkg/apis/helm.fluxcd.io/v1/types.go#L253-L263)?). A Helm Exporter approach, i.e. having a counter with a value to status mapping, would help too, but I'm not sure it's a recommended usage of Prometheus.

----

I just noticed there's an [`ErrChartSync`](https://github.com/fluxcd/helm-operator/blob/master/pkg/operator/operator.go#L38-L40) declared, meant to be used as an event reason, but it's not used. ~I'll try to fix that.~ It's actually gone on the `helm-v3-dev` branch. As active development is being made on it, I'd rather wait its changes to reach `master` before eventually thinking about adding new events (FYI @hiddeco).
