### ISSUE TITLE
ChartFetchFailed error in HelmRelease on updating Helm-operator image version

### ISSUE THREAD

**Issue by sredhu37** [fluxcd/helm-operator#644]
I am facing an issue when trying to upgrade my helm-operator image version from 1.0.0-rc7 to 1.4.0.

helm-operator chart version: 1.4.0
helm-operator image version: Upgrading from 1.0.0-rc7 to 1.4.0

Steps to reproduce the issue:
1. Deploy a HelmRelease which points to a git repository.
2. Update helm-operator image to 1.4.0. Pod restarts with the new image version.
3. Push some change to git repo mentioned in Step 1.
4. You will notice the ChartFetchFailed error in the HelmRelease. (Image attached)

![image](https://user-images.githubusercontent.com/8821336/146302946-f614d18e-1942-4eb0-b8b8-e083c3e94c19.png)

HelmRelease file:
```apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: sr-credentials
  namespace: yocto
spec:
  releaseName: sr-credentials
  targetNamespace: yocto
  rollback:
    enable: true
  chart:
    git: "https://gerrit.<redacting-this>.com/gerrit/MN/SCMTA/scminfra/k8s-configs/yocto.git"
    ref: "users/redhu/helm3test"
    path: "jenkins/credentials"
```

Does anyone know how to resolve it (except recreating the HelmRelease)?

**Comment by kingdonb** [comment]
Hello, I think I found your question in a slack thread here: https://cloud-native.slack.com/archives/CLAJ40HV3/p1639623932191100

It will not be possible to help without more detail, including perhaps the manifest that you deployed.

There are some places where I might spot a typo, like for example the `git` source must be of the form `git@github.com:user/repo` which differs from the requirements what you'll find in current releases of Flux. Like for example in (https://github.com/fluxcd/helm-operator/issues/275)

There have been some breaking changes, and if it's possible for you to migrate, we'd much more recommend that you use Flux v2 which has Helm Controller that solves a lot of common Helm Operator issues right out of the gate, moreover that it is actively maintained and Helm Operator is in maintenance mode (#546)

Can you at least post the `HelmRelease` yaml? Without that, I'm afraid I don't have a ghost of chance at solving your issue.

**Comment by sredhu37** [comment]
I have updated the original question and added the HelmRelease yaml code there.

**Comment by kingdonb** [comment]
I think this issue might be related to #394 – try setting `--git-timeout` to a value greater than 2m – you could be getting this error message due to timeout during git clone operations.

**Comment by kingdonb** [comment]
Please let us know if this resolves your issue. If there is no response this week, I think we can close the issue.
