### ISSUE TITLE
The helm repository does not support authentication

### ISSUE THREAD

**Issue by wujiangfa-xlauncher** [fluxcd/helm-operator#650]
**Describe the bug**

<img width="627" alt="image" src="https://user-images.githubusercontent.com/53930349/165878148-df2390a5-4ea0-40cf-a31d-539f6ed1c269.png">

**To Reproduce**

Steps to reproduce the behaviour:
1. Provide the Helm Operator install instructions
2. Provide a HelmRelease example
3. Post the HelmRelease status, you can get this by running `kubectl describe helmrelease <name>`

**Expected behavior**

**Logs**

If applicable, please provide logs. In a standard stand-alone installation, you'd get this by running `kubectl logs deploy/flux-helm-operator -n fluxcd`.

**Additional context**

- Helm Operator version: 
- Kubernetes version:
- Git provider:
- Helm repository provider:

**Comment by hiddeco** [comment]
Further development on the Helm Operator other than the required maintenance work once in awhile has stalled. Its successor is https://github.com/fluxcd/helm-controller.

Authentication is possible through file mounts: https://fluxcd.io/legacy/helm-operator/references/chart/#use-a-custom-helm-repository
