### ISSUE TITLE
ServiceAccount annotations are being overriden?

### ISSUE THREAD

**Issue by heprotecbuthealsoattac** [fluxcd/helm-operator#70]
Hi,

I'm trying to install cert-manager using their chart: https://github.com/jetstack/cert-manager/tree/master/deploy/charts/cert-manager
However when I specify `serviceAccount.annotations` only annotation I can see on the created service accounts is: `flux.weave.works/antecedent: cert-manager:helmrelease/cert-manager`

**Comment by biwwy0** [comment]
That's one very frustrating bug! Killed few hours figuring it out.

**Comment by stefansedich** [comment]
@heprotecbuthealsoattac do you have an example HelmRelease replicating this? and what version of Helm were you using?

**Comment by biwwy0** [comment]
It works if annotation is set directly from chart defined `values.yaml`, but if we use values from HelmRelease it doesn't. Tried `values:` and from ConfigMap

Example of mine is here:

```---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: infra
spec:
  releaseName: cert-manager
  targetNamespace: infra
  chart:
    git: git@XXXX.com/XXXX/XXXX.git
    path: charts/cert-manager
    ref: develop
    values:
      serviceAccount:
        create: true
        name: cert-manager
        annotations:
          eks.amazonaws.com/role-arn: arn:aws:iam::XXXXXX:role/stage-cert-manager```

**Comment by stefansedich** [comment]
@biwwy0 is there an indent issue in the example? values looks to be at the wrong level.

**Comment by biwwy0** [comment]
Jesus, our lord in Heaven. 

`It's never indent. It can't be indent. It was indent.`

I was just surprised to find the issue open with exactly same problem I have so I thought two persons can't have the same mistake for same resource. Also I looked at the helm-operator code and couldn't figure how on earth could that be overwritten.

Thank you @stefansedich! I guess bug was in our heads.

**Comment by hiddeco** [comment]
Glad you two could work it out @biwwy0 @stefansedich :sun_with_face:
