### ISSUE TITLE
Cmpare OperatorSdk helm vs helm-operator

### ISSUE THREAD

**Issue by ysaakpr** [fluxcd/helm-operator#78]
This is mostly an informational issue to understand from the team of fluxcd. I am wondering how [operator sdk](https://github.com/operator-framework/operator-sdk/blob/master/doc/helm/user-guide.md) and helm operator can work similarly. 
How could we compare both these and decide on when to choose what. Are there any fundamental differences between the two.

**Comment by hiddeco** [comment]
This is an :apple::orange: comparison imho.

The operator SDK is a software development kit to create operators. The guide you are referring to documents how you can create an operator which reacts to a certain custom resource you create (e.g. `Nginx`) and installs a specific chart release. So the operator in this example will only be able to install Nginx charts of the same version.

The Helm operator on the other hand has a single custom resource which allows you to install any chart using a single custom resource (`HelmRelease`), without having to build the operator yourself.

**Comment by ysaakpr** [comment]
Got it..thanks for the confirmation.
