### ISSUE TITLE
Release does not belong to HelmRelease, this may be an indication that multiple HelmReleases with the same release name exist.

### ISSUE THREAD

**Issue by mar1n3r0** [fluxcd/helm-operator#81]
**Describe the bug**
The automated deployment stopped working. The status of the helmRelease is deployed but it doesn't detect changes in image versions from docker repository.
**To Reproduce**
Steps to reproduce the behaviour:
https://github.com/fluxcd/helm-operator-get-started

**Expected behavior**
The automated releases based on image versions to work.
**Logs**
If applicable, please provide logs. In a standard stand-alone installation, you'd get this by running `kubectl logs -n default deploy/flux-helm-operator`.

textPayload: "ts=2019-10-21T13:17:31.407051541Z caller=chartsync.go:374 component=chartsync warning="release 'office-hub-stg' does not belong to HelmRelease, this may be an indication that multiple HelmReleases with the same release name exist" resource=stg:helmrelease/office-hub-stg

**Additional context**
Add any other context about the problem here, e.g 
- Helm operator version: 1.14.2
- Kubernetes version: 1.13.7-gke.24
- Git provider: Bitbucket
- Container registry provider: Docker Hub

**Comment by hiddeco** [comment]
> Helm operator version: 1.14.2

This is likely your Flux version, and not the Helm operator version you are running. There has been a fix (#56) for the behaviour you are describing in the second latest release (`1.0.0-rc2`).

**Comment by mar1n3r0** [comment]
Thanks do you know how can I view the Helm operator version currently running ?

**Comment by stefanprodan** [comment]
We use the version to tag the container image: `kubectl -n flux get deploy/flux-helm-operator -oyaml | grep image`

**Comment by mar1n3r0** [comment]
helm-operator:0.10.1 is what I get. Is that pre-1.0.0 ?

**Comment by mar1n3r0** [comment]
An upgrade to 1.0.0-rc2 did indeed solve the issue. Marking this as resolved.
