### ISSUE TITLE
Upgrade helm to v2.16.1

### ISSUE THREAD

**Issue by karuppiah7890** [fluxcd/helm-operator#85]
**Describe the feature**
Update helm to v2.16.1 . I see it's currently v2.14.3 😄 

**Expected behavior**
Better experience because of the bug fixes from the new releases
https://github.com/helm/helm/releases/tag/v2.15.0
https://github.com/helm/helm/releases/tag/v2.15.1
https://github.com/helm/helm/releases/tag/v2.16.0

https://github.com/helm/helm/releases/tag/v2.16.1 will be released only later, but we need to wait for it because of this - https://github.com/fishworks/fish-food/pull/458#issuecomment-551162195

**Comment by karuppiah7890** [comment]
I'll raise a PR for this 😄

**Comment by hiddeco** [comment]
Closed via #107.
