### ISSUE TITLE
Update helm to v3 in helm-v3-dev branch

### ISSUE THREAD

**Issue by karuppiah7890** [fluxcd/helm-operator#91]
**Describe the feature**
Update helm to v3 in helm-v3-dev branch

**Comment by torstenwalter** [comment]
[helm 3 RC1](https://github.com/helm/helm/releases/tag/v3.0.0-rc.1) is out since yesterday

**Comment by slenky** [comment]
I am trying to upgrade it but facing an issues with k8s version in go.mod:

```
build github.com/fluxcd/helm-operator/cmd/helm-operator: cannot load k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1: module k8s.io/apiextensions-apiserver@latest found (v0.0.0-20191028232452-c47e10e6d5a3, replaced by k8s.io/apiextensions-apiserver@v0.0.0-20190819143637-0dbe462fe92d), but does not contain package k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1
```
or
```
k8s.io/kubectl/pkg/cmd/util: module k8s.io/kubectl@latest found (v0.0.0-20191027032433-6b77b0790ab4, replaced by k8s.io/kubectl@v0.0.0-20190602132728-7075c07e78bf), but does not contain package k8s.io/kubectl/pkg/cmd/util
```
:(

**Comment by marshallford** [comment]
[Helm v3.0.0-rc.3](https://github.com/helm/helm/releases/tag/v3.0.0-rc.3) is out.

**Comment by karuppiah7890** [comment]
@slenky Do you want some help? May be we could remote pair and work on this? I tried it too, and faced the same errors. But I think I know how to get around them

**Comment by karuppiah7890** [comment]
Let me know. I would be willing to help 😄

**Comment by marshallford** [comment]
[Helm v3](https://github.com/helm/helm/releases/tag/v3.0.0) is out!

**Comment by karuppiah7890** [comment]
Shall I pick this up?
