### ISSUE TITLE
Helm client in operator gets namespace wrong

### ISSUE THREAD

**Issue by gaveezy** [fluxcd/helm-operator#93]
**Describe the bug**
I try to run install a chart from operator pod but it seems helm client get the namespace wrong.
Get pods
```
kubectl get pods -n flux
```
Output
```
flux-5878766c4b-2mf42                 1/1     Running   0          37m
flux-helm-operator-77d464dbc4-pb5ns   1/1     Running   0          37m
flux-memcached-676b496574-28f8l       1/1     Running   0          37m
```
Open a shell to operator
```
keti -n flux flux-helm-operator-77d464dbc4-pb5ns /bin/sh
```
Output
```
/home/flux # 
```
With the `ls` it works
```
/home/flux # helm --tls --tls-verify \
  --tls-ca-cert /etc/fluxd/helm-ca/ca.crt \
  --tls-cert /etc/fluxd/helm/tls.crt \
  --tls-key /etc/fluxd/helm/tls.key \
  --tls-hostname tiller-deploy.kube-system \
  ls
```
Output
```
audit-logging         	1       	Tue Oct 29 11:22:23 2019	DEPLOYED	audit-logging-3.2.0         	           	kube-system 
auth-apikeys          	1       	Tue Oct 29 11:17:41 2019	DEPLOYED	auth-apikeys-3.2.0          	           	kube-system 
auth-idp              	1       	Tue Oct 29 11:17:39 2019	DEPLOYED	auth-idp-3.2.0              	           	kube-system 
auth-pap              	1       	Tue Oct 29 11:17:43 2019	DEPLOYED	auth-pap-3.2.0              	           	kube-system 
....
```
But when install
```
/home/flux # helm --tls --tls-verify \
  --tls-ca-cert /etc/fluxd/helm-ca/ca.crt \
  --tls-cert /etc/fluxd/helm/tls.crt \
  --tls-key /etc/fluxd/helm/tls.key \
  --tls-hostname tiller-deploy.kube-system \
  install --name dokuwiki-test stable/dokuwiki --namespace default
```
Output:
```
Error: Not authorized: Client is not authorized to install a release, into namespace:
dokuwiki-test default
```

Install works when try from another helm client, same version.
```
Client: &version.Version{SemVer:"v2.12.3", GitCommit:"eecf22f77df5f65c823aacd2dbd30ae6c65f186e", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.12.3+icp", GitCommit:"34e12adfe271fd157db8f9745affe84c0f603809", GitTreeState:"clean"}
```

**To Reproduce**
Steps to reproduce the behaviour:

0. Install v1 CRD, flux-operator 1.0.0-rc3 (custom build with helm version set to 2.12.3)
1. Install flux-operator
2. Open a shell to deployment/flux-helm-operator
3. Use helm to install any chart

**Expected behavior**
Expected the chart to be installed successfully

**Additional context**
Add any other context about the problem here, e.g 
- Helm operator version: 1.0.0-rc3
- Kubernetes version: v1.13.5+icp
- Git provider: github
- Container registry provider: docker.io

**Comment by gdesio75** [comment]
I found the same. Pls, could you provide further info about a the issue has been addressed?

**Comment by gaveezy** [comment]
I ended up using helm v3 with new version of the operator. Not sure about the bug resolve status.

**Comment by davidkarlsen** [comment]
I think that's an ICP issue with their custom Tiller / authorization - I see it often on ICP. Killing `auth-idp` pods seem to help.
By using helm3 you avoid tiller of course.

**Comment by gaveezy** [comment]
> I think that's an ICP issue with their custom Tiller / authorization - I see it often on ICP. Killing `auth-idp` pods seem to help.
> By using helm3 you avoid tiller of course.

That's right. As I moved to helm 3, this issue is not relevant anymore.
